In [1]:
%%html
<style type='text/css'>
.CodeMirror{
    font-family: Inconsolata;
    font-size: 13px;
}

div.output_area pre {
    font-family: Inconsolata;
    font-size: 11px;
}

div.text_cell_render {
    font-family: Inconsolata;
    font-size: 13px;
}
</style>

In [2]:
import pandas as pd
import os, shutil
import numpy as np
import matplotlib
import sys; sys.path.append('..')
import pickle
import requests
import torch

from queue import Queue
from tqdm.notebook import tqdm, tqdm_notebook
from collections import defaultdict

path_ddi_dataset = r"/data/data2/041/datasets/DDI"
path_iii_dataset = r"/data/data2/041/datasets/mimic-iii-clinical-database-1.4"

## TWOSIDES

In [55]:
df_twosides = pd.read_csv(os.path.join(path_ddi_dataset, "TWOSIDES.csv.gz"))
df_twosides["drug_1_rxnorn_id"] = df_twosides["drug_1_rxnorn_id"].astype("string")

df_twosides.info()

/data/data2/041/envs/LERS2/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3269: DtypeWarning: Columns (0,2,4,6,7,8,9,10,11,12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42920391 entries, 0 to 42920390
Data columns (total 13 columns):
 #   Column                    Dtype
---  ------                    -----
 0   drug_1_rxnorn_id          string
 1   drug_1_concept_name       object
 2   drug_2_rxnorm_id          object
 3   drug_2_concept_name       object
 4   condition_meddra_id       object
 5   condition_concept_name    object
 6   A                         object
 7   B                         object
 8   C                         object
 9   D                         object
 10  PRR                       object
 11  PRR_error                 object
 12  mean_reporting_frequency  object
dtypes: object(12), string(1)
memory usage: 4.2+ GB

In [56]:
df_twosides.head()

,drug_1_rxnorn_id,drug_1_concept_name,drug_2_rxnorm_id,drug_2_concept_name,condition_meddra_id,condition_concept_name,A,B,C,D,PRR,PRR_error,mean_reporting_frequency
0,10355,Temazepam,136411,sildenafil,10003239,Arthralgia,7,149,24,1536,2.91667,0.421275,0.0448718
1,1808,Bumetanide,7824,Oxytocin,10003239,Arthralgia,1,13,2,138,5.0,1.19224,0.0714286
2,221147,POLYETHYLENE GLYCOL 3350,5521,Hydroxychloroquine,10003239,Arthralgia,6,103,20,1070,3.0,0.454505,0.0550459
3,10324,Tamoxifen,8640,Prednisone,10012735,Diarrhoea,18,123,35,1375,5.14286,0.276271,0.12766
4,10355,Temazepam,136411,sildenafil,10012735,Diarrhoea,2,154,37,1523,0.540541,0.721093,0.0128205

In [64]:
df_twosides.tail()

,drug_1_rxnorn_id,drug_1_concept_name,drug_2_rxnorm_id,drug_2_concept_name,condition_meddra_id,condition_concept_name,A,B,C,D,PRR,PRR_error,mean_reporting_frequency
42920386,6142,Ketoprofen,88249,montelukast,10050954,Activities of daily living impaired,1,51,1,519,10.0,1.40671,0.019231
42920387,6142,Ketoprofen,88249,montelukast,10052302,Impaired work ability,1,51,1,519,10.0,1.40671,0.019231
42920388,6142,Ketoprofen,88249,montelukast,10053762,Off label use,3,49,13,507,2.30769,0.623781,0.057692
42920389,6142,Ketoprofen,88249,montelukast,10020772,Hypertension,1,51,4,516,2.5,1.10853,0.019231
42920390,6142,Ketoprofen,88249,montelukast,10070863,Toxicity to various agents,1,51,3,517,3.33333,1.1455,0.019231

---

# MAPPING

1. NDC to RXCUI (done in `preprocess_drug.ipynb`)
2. RXCUI to ATC4
3. ATC4 to CID

## RXCUI2ATC4

In [138]:
df_ndc2atc = pd.read_csv(os.path.join(path_ddi_dataset, "ndc2atc_level4.csv"))
df_ndc2atc.drop(columns=['YEAR','MONTH','NDC'], inplace=True)
df_ndc2atc

          RXCUI   ATC4
0        853004  C01BA
1       1551300  A10BJ
2       1551300  A10BJ
3       1551306  A10BJ
4       1551306  A10BJ
...         ...    ...
318252   543484  D07AC
318253   543484  C05AA
318254   543484  D07AC
318255  1482689  D01AC
318256  1482689  D01AC

[318257 rows x 2 columns]

In [139]:
df_ndc2atc.RXCUI.value_counts()

310965     5585
204602     4709
581660     3630
312172     3365
106258     2457
           ...
1242136       1
1053146       1
211199        1
860898        1
352213        1
Name: RXCUI, Length: 11478, dtype: int64

In [140]:
df_ndc2atc.drop_duplicates(subset=['RXCUI'], inplace=True)
df_ndc2atc.RXCUI.value_counts()

311296     1
903884     1
898689     1
1094323    1
311989     1
          ..
1736053    1
1789192    1
830839     1
152952     1
1116159    1
Name: RXCUI, Length: 11478, dtype: int64

In [188]:
df_drug_ndc_feat = pd.read_csv(os.path.join(path_iii_dataset, "DRUGS_NDC_FEAT.csv.gz"))
df_drug_ndc_feat.drop(columns=['Unnamed: 0'], inplace=True)
df_drug_ndc_feat.drop(columns=[
    'DRUG_TYPE_MAIN_Proportion', 
    'DRUG_TYPE_BASE_Proportion', 
    'DRUG_TYPE_ADDITIVE_Proportion', 
    'FORM_UNIT_DISP_Freq_1', 
    'FORM_UNIT_DISP_Freq_2', 
    'FORM_UNIT_DISP_Freq_3', 
    'FORM_UNIT_DISP_Freq_4', 
    'FORM_UNIT_DISP_Freq_5'], inplace=True)
df_drug_ndc_feat.sort_values(by="NDC", inplace=True)
df_drug_ndc_feat['idx'] = range(len(df_drug_ndc_feat))
df_drug_ndc_feat.head()

      NDC  rxnorm_id  idx
4121  1.0        NaN    0
4122  2.0        NaN    1
4123  3.0        NaN    2
4124  4.0        NaN    3
4125  5.0        NaN    4

In [223]:
df_drug_ndc_feat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4294 entries, 4121 to 4120
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NDC        4294 non-null   float64
 1   rxnorm_id  4101 non-null   float64
 2   idx        4294 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 134.2 KB

In [222]:
df_drug_ndc_feat_ndc_not_real = df_drug_ndc_feat[df_drug_ndc_feat.NDC < 1000].copy()
df_drug_ndc_feat_ndc_not_real.rename(columns={'rxnorm_id': 'RXCUI'}, inplace=True)
df_drug_ndc_feat_ndc_not_real

        NDC  RXCUI  idx
4121    1.0    NaN    0
4122    2.0    NaN    1
4123    3.0    NaN    2
4124    4.0    NaN    3
4125    5.0    NaN    4
...     ...    ...  ...
4289  170.0    NaN  168
4290  171.0    NaN  169
4291  172.0    NaN  170
4292  173.0    NaN  171
4293  174.0    NaN  172

[173 rows x 3 columns]

In [220]:
temp_df = df_drug_ndc_feat[df_drug_ndc_feat.NDC > 1000]
df_drug_ndc_feat_ndc_real_rxcui_not_exist = temp_df[temp_df.rxnorm_id.isnull()].copy()
df_drug_ndc_feat_ndc_real_rxcui_not_exist.rename(columns={'rxnorm_id': 'RXCUI'}, inplace=True)
df_drug_ndc_feat_ndc_real_rxcui_not_exist

               NDC  RXCUI   idx
416   2.606320e+07    NaN   589
1351  1.320001e+08    NaN  1524
1798  3.380404e+08    NaN  1971
2569  8.290002e+09    NaN  2742
2576  8.881200e+09    NaN  2749
2639  1.093900e+10    NaN  2812
2666  1.253901e+10    NaN  2839
2677  1.512702e+10    NaN  2850
2682  1.656301e+10    NaN  2855
2684  1.683709e+10    NaN  2857
2714  1.800633e+10    NaN  2887
2820  4.768202e+10    NaN  2993
3343  5.456919e+10    NaN  3516
3370  5.456947e+10    NaN  3543
3371  5.456947e+10    NaN  3544
3419  5.504512e+10    NaN  3592
4015  6.668904e+10    NaN  4188
4110  7.214009e+10    NaN  4283
4118  8.770107e+10    NaN  4291
4120  8.770109e+10    NaN  4293

In [190]:
df_drug_ndc_feat_ndc_real = df_drug_ndc_feat[df_drug_ndc_feat.NDC > 1000].copy()
df_drug_ndc_feat_ndc_real.dropna(inplace=True)
df_drug_ndc_feat_ndc_real

               NDC  rxnorm_id   idx
0     2.050101e+06   207882.0   173
1     2.140701e+06   853004.0   174
2     2.144401e+06   208815.0   175
3     2.202402e+06   313009.0   176
4     2.322930e+06   352320.0   177
...            ...        ...   ...
4114  7.431200e+10   309604.0  4287
4115  7.431200e+10   313896.0  4288
4116  7.811200e+10  1101849.0  4289
4117  7.951105e+10   669319.0  4290
4119  8.770108e+10  1049906.0  4292

[4101 rows x 3 columns]

In [191]:
df_drug_ndc_feat_ndc_real.rename(columns={'rxnorm_id': 'RXCUI'}, inplace=True)
df_drug_ndc_feat_ndc_real

               NDC      RXCUI   idx
0     2.050101e+06   207882.0   173
1     2.140701e+06   853004.0   174
2     2.144401e+06   208815.0   175
3     2.202402e+06   313009.0   176
4     2.322930e+06   352320.0   177
...            ...        ...   ...
4114  7.431200e+10   309604.0  4287
4115  7.431200e+10   313896.0  4288
4116  7.811200e+10  1101849.0  4289
4117  7.951105e+10   669319.0  4290
4119  8.770108e+10  1049906.0  4292

[4101 rows x 3 columns]

In [192]:
df_drug_ndc_feat_ndc_real = df_drug_ndc_feat_ndc_real.merge(df_ndc2atc, how='left', on=["RXCUI"])
df_drug_ndc_feat_ndc_real

               NDC      RXCUI   idx   ATC4
0     2.050101e+06   207882.0   173    NaN
1     2.140701e+06   853004.0   174  C01BA
2     2.144401e+06   208815.0   175    NaN
3     2.202402e+06   313009.0   176  A12CA
4     2.322930e+06   352320.0   177  N06BA
...            ...        ...   ...    ...
4096  7.431200e+10   309604.0  4287    NaN
4097  7.431200e+10   313896.0  4288    NaN
4098  7.811200e+10  1101849.0  4289    NaN
4099  7.951105e+10   669319.0  4290    NaN
4100  8.770108e+10  1049906.0  4292  D04AA

[4101 rows x 4 columns]

In [ ]:
# df_drug_ndc_feat_ndc_real['ATC4'] = df_drug_ndc_feat_ndc_real['ATC4'].map(lambda x: x[:4])
# df_drug_ndc_feat_ndc_real

In [194]:
df_drug_ndc_feat_ndc_real_atc4_exist = df_drug_ndc_feat_ndc_real[df_drug_ndc_feat_ndc_real.ATC4.notnull()]
df_drug_ndc_feat_ndc_real_atc4_exist

               NDC      RXCUI   idx   ATC4
1     2.140701e+06   853004.0   174  C01BA
3     2.202402e+06   313009.0   176  A12CA
4     2.322930e+06   352320.0   177  N06BA
5     2.323560e+06   596928.0   178  N06AX
6     2.324001e+06   596932.0   179  N06AX
...            ...        ...   ...    ...
4083  6.854603e+10  1111642.0  4273  L03AX
4086  6.877401e+10   197516.0  4276  J01FA
4088  6.885000e+10   995605.0  4278  J04AK
4089  6.885000e+10   995609.0  4279  J04AK
4100  8.770108e+10  1049906.0  4292  D04AA

[2885 rows x 4 columns]

In [195]:
df_drug_ndc_feat_ndc_real_atc4_exist.ATC4.value_counts()

A01AC    61
N02AA    60
N03AX    47
C09AA    40
N05AX    38
         ..
D10AE     1
C01DX     1
A10BF     1
N05AG     1
M01AE     1
Name: ATC4, Length: 346, dtype: int64

In [196]:
df_drug_ndc_feat_ndc_real_ATC4_unique = df_drug_ndc_feat_ndc_real_atc4_exist.drop_duplicates(subset=['ATC4'])
df_drug_ndc_feat_ndc_real_ATC4_unique

               NDC     RXCUI   idx   ATC4
1     2.140701e+06  853004.0   174  C01BA
3     2.202402e+06  313009.0   176  A12CA
4     2.322930e+06  352320.0   177  N06BA
5     2.323560e+06  596928.0   178  N06AX
9     2.411230e+06  212405.0   182  N05AH
...            ...       ...   ...    ...
3937  6.476402e+10  617768.0  4126  A06AX
3947  6.519700e+10  861404.0  4136  C04AX
3967  6.584702e+10  883708.0  4156  C01DX
3988  6.658204e+10  352304.0  4177  C10AX
4024  6.742500e+10  582692.0  4214  B06AA

[346 rows x 4 columns]

In [148]:
list_atc4_exist = list(df_drug_ndc_feat_ndc_real_ATC4_unique.ATC4.unique())
list_atc4_exist

['C01BA',
 'A12CA',
 'N06BA',
 'N06AX',
 'N05AH',
 'G03XC',
 'B01AC',
 'A10AB',
 'H05AA',
 'A01AC',
 'L01XE',
 'J01CE',
 'L01XX',
 'J05AF',
 'L04AA',
 'J01DF',
 'J01GB',
 'J05AE',
 'C10AA',
 'J05AB',
 'N03AE',
 'D01AE',
 'A11CC',
 'M05BA',
 'C03CA',
 'L03AB',
 'J05AX',
 'J05AH',
 'L01BC',
 'N04BX',
 'S01EC',
 'H03BA',
 'A01AB',
 'D11AX',
 'B02BA',
 'C03CC',
 'R03DC',
 'C01EB',
 'N02CC',
 'A10BH',
 'A04AD',
 'C09CA',
 'A02BA',
 'N04AC',
 'J01DH',
 'C03AA',
 'J02AX',
 'L01AA',
 'B01AX',
 'N05AB',
 'C03DB',
 'C07AG',
 'L01BB',
 'B01AE',
 'N06AF',
 'N04BC',
 'H03AA',
 'P02CA',
 'D04AA',
 'N02AA',
 'N05CA',
 'N05BA',
 'A02BC',
 'N05CF',
 'A06AH',
 'C07AB',
 'L01XC',
 'J01AA',
 'D07AA',
 'G03AC',
 'D06AX',
 'C10AC',
 'A10BB',
 'G03BA',
 'D10AF',
 'G02AD',
 'C01EA',
 'J05AG',
 'C01BD',
 'G04BD',
 'L01DB',
 'J01XX',
 'L02BG',
 'A07EC',
 'B02AA',
 'J04AB',
 'S01EE',
 'L01AD',
 'L01XA',
 'R05CB',
 'J01CF',
 'J01CA',
 'A06AA',
 'M01AB',
 'P03AC',
 'L04AD',
 'C01CA',
 'L01XD',
 'P01BA',
 'C03DA',
 'A02BB',
 'A10BF',
 'D07AB',
 'J01MA',
 'C08CA',
 'A10BG',
 'N06AB',
 'A03BA',
 'C02AC',
 'A09AA',
 'G03DA',
 'A06AB',
 'D08AG',
 'R03DA',
 'R01AC',
 'N03AX',
 'M01CC',
 'C09AA',
 'N02BE',
 'N02AX',
 'A01AD',
 'V03AB',
 'C07AA',
 'G03CA',
 'J01CR',
 'C02CA',
 'J02AC',
 'D01AC',
 'N05AE',
 'N07AA',
 'A07EA',
 'V03AE',
 'N03AF',
 'N02AE',
 'N01BC',
 'D07AC',
 'N05AD',
 'C01BB',
 'N02AB',
 'N07BC',
 'L04AX',
 'N05CD',
 'A02AC',
 'R05DA',
 'C01AA',
 'A06AD',
 'A07DA',
 'A03FA',
 'N03AA',
 'A03AB',
 'B01AA',
 'N04BA',
 'D10AD',
 'G01AG',
 'R01AA',
 'S01FA',
 'S01EA',
 'C05AD',
 'A12AA',
 'A02AB',
 'R06AE',
 'J01FA',
 'G04BE',
 'N03AB',
 'N03AD',
 'C01DA',
 'D05AX',
 'B01AB',
 'N02AF',
 'N03AG',
 'N05CM',
 'N01AX',
 'C02DD',
 'B05XA',
 'L02AE',
 'J05AR',
 'M03AC',
 'B05CX',
 'C10AB',
 'G01AD',
 'B05CB',
 'A12BA',
 'B05AA',
 'H01BA',
 'N07XX',
 'J01FG',
 'G02CB',
 'G02AB',
 'H05BA',
 'H01CB',
 'N06AA',
 'A05AA',
 'N06DA',
 'L04AC',
 'A10BX',
 'V03AC',
 'C09XA',
 'L03AC',
 'R06AX',
 'L01AX',
 'J05AP',
 'R03AC',
 'P02BA',
 'N06BC',
 'A10BA',
 'L03AX',
 'A04AA',
 'A02BX',
 'A10AE',
 'D06BB',
 'J01EC',
 'C05AA',
 'M01AC',
 'L02BA',
 'J05AC',
 'D06AA',
 'H02AA',
 'G04CA',
 'R05CA',
 'A02AA',
 'A09AB',
 'N04BB',
 'A01AA',
 'N07BA',
 'M04AC',
 'M03BA',
 'J01DB',
 'D05BB',
 'J01XE',
 'M03CA',
 'A07AA',
 'D07AD',
 'C08DA',
 'L02BB',
 'N05BE',
 'P01BD',
 'J01DC',
 'P01AX',
 'P01BB',
 'R03AK',
 'G04BX',
 'B03BB',
 'C02DB',
 'N05BB',
 'B03AA',
 'H03BB',
 'A14AA',
 'N01BB',
 'J05AD',
 'J01CG',
 'C05AE',
 'V04CC',
 'J01DD',
 'C01CE',
 'M04AB',
 'J01EA',
 'C02DC',
 'N01AH',
 'L01CD',
 'M03AB',
 'D08AX',
 'J01DI',
 'R05DB',
 'N06DX',
 'D11AH',
 'R01AX',
 'B03BA',
 'P03AB',
 'R01BA',
 'C05BB',
 'M02AB',
 'A03AA',
 'N07BB',
 'S01KA',
 'A07BA',
 'C02DA',
 'A11DA',
 'N05AA',
 'L01DC',
 'L01CA',
 'L01CB',
 'A06AG',
 'N05AC',
 'N02BA',
 'M03BX',
 'G02CC',
 'N05AX',
 'N07AX',
 'D06BA',
 'M01AE',
 'D08AL',
 'P01BC',
 'J06BB',
 'A07EB',
 'S01ED',
 'R02AB',
 'N04BD',
 'J07AF',
 'M01AX',
 'D10AX',
 'N07AB',
 'B01AD',
 'A16AA',
 'L03AA',
 'B01AF',
 'C03BA',
 'J04AC',
 'N04AA',
 'R06AB',
 'C02AB',
 'M04AA',
 'N05AF',
 'L01BA',
 'J04AK',
 'B02BC',
 'C01BC',
 'L01XB',
 'C04AB',
 'H04AA',
 'A11GA',
 'L01AC',
 'V03AF',
 'B03XA',
 'H05BX',
 'L02BX',
 'N05AG',
 'L04AB',
 'C03XA',
 'L01AB',
 'D10AE',
 'S01EB',
 'J01DE',
 'A03AD',
 'S01HA',
 'S01AD',
 'H01BB',
 'R06AA',
 'A11CA',
 'H01AA',
 'A11HA',
 'P01CX',
 'A06AX',
 'C04AX',
 'C01DX',
 'C10AX',
 'B06AA']

## ATC2CID

In [205]:
cid_atc = os.path.join(path_ddi_dataset, "drug-atc.csv")
cid2atc_dic = {}
with open(cid_atc, 'r') as f:
    for line in f:
        line_ls = line[:-1].split(',')
        cid = line_ls[0]
        atcs = [act[:5] for act in line_ls[1:]]
        cid2atc_dic[cid] = atcs

cid2atc_dic

{'CID000003015': ['G03HA'],
 'CID000004011': ['N06AA'],
 'CID000071273': ['N01BB'],
 'CID000062816': ['C10AC'],
 'CID000052421': ['D07AC', 'V01AA', 'V01AA'],
 'CID000056339': ['N03AB'],
 'CID000077992': ['N02CC'],
 'CID000005300': ['L01AD'],
 'CID000222786': ['H02AB', 'S01BA'],
 'CID000071301': ['C07AB'],
 'CID000004870': ['C03AA'],
 'CID000004873': ['A12BA', 'B05XA'],
 'CID000002142': ['D06AX', 'J01GB', 'S01AA'],
 'CID000002141': ['V03AF'],
 'CID000131536': ['J05AE'],
 'CID000001775': ['N03AB', 'N03AB', 'N03AB'],
 'CID000003305': ['M05BA', 'M05BB'],
 'CID000005454': ['N05AF'],
 'CID000003308': ['M01AB'],
 'CID000004909': ['D08AC', 'S03AA', 'S01AX', 'R01AX', 'R02AA', 'N03AA'],
 'CID000004908': ['P01BA'],
 'CID000002099': ['A03AE'],
 'CID000054688': ['J01FA'],
 'CID000002092': ['G04CA'],
 'CID000005503': ['A10BB'],
 'CID000004536': ['G03AC'],
 'CID006918453': ['M01CB'],
 'CID000003706': ['J05AE'],
 'CID000005408': ['G03BA', 'G03BA', 'G03EK'],
 'CID000004497': ['C08CA'],
 'CID000004493': ['L02BB'],
 'CID000003219': ['S01GX'],
 'CID000002435': ['S01EA'],
 'CID000003121': ['N03AG'],
 'CID000040159': ['P03AC'],
 'CID000005878': ['A14AA'],
 'CID000002554': ['N03AF'],
 'CID000002550': ['C09AA'],
 'CID000002551': ['N07AB', 'S01EB'],
 'CID000010100': ['N02AC', 'N02AC', 'N02AC'],
 'CID000002559': ['J01CA'],
 'CID000443871': ['A10BX'],
 'CID000003059': ['N02BA'],
 'CID000019090': ['G03AC', 'G03DB', 'L02AB', 'G03DB'],
 'CID000059768': ['C07AB'],
 'CID004183806': ['A02BB'],
 'CID000176870': ['L01XE'],
 'CID000004473': ['C08CA'],
 'CID000003440': ['C03CA'],
 'CID000003449': ['N06DA'],
 'CID000003685': ['L01DB'],
 'CID000003937': ['C09AA'],
 'CID004630253': ['D07AB', 'S01BA'],
 'CID000018140': ['L01XX'],
 'CID000000727': ['P03AB', 'D08AE'],
 'CID004475485': ['C10AA'],
 'CID000077993': ['N02CC'],
 'CID000148211': ['A04AA'],
 'CID000072938': ['J01MA'],
 'CID000002153': ['R03DA', 'R03DA'],
 'CID000002156': ['C01BD'],
 'CID000008953': ['B05XA', 'B05CB'],
 'CID000005203': ['N06AB'],
 'CID000005206': ['N01AB'],
 'CID005281104': ['H05BX'],
 'CID000004917': ['N05AB'],
 'CID000004914': ['C05AD',
  'D04AB',
  'J01CE',
  'N01BA',
  'N01BA',
  'S01HA',
  'S01HA',
  'C01BA'],
 'CID000004913': ['C01BA'],
 'CID000003339': ['C10AB'],
 'CID000004911': ['M04AB'],
 'CID000213039': ['J05AE'],
 'CID006436173': ['A07AA', 'D06AX'],
 'CID000002088': ['M05BA'],
 'CID000002082': ['P02CA'],
 'CID000005515': ['L01XX'],
 'CID000005516': ['L02BA'],
 'CID000002145': ['L02BG'],
 'CID000005512': ['G04BD'],
 'CID000005735': ['N05CF'],
 'CID000005734': ['N03AX'],
 'CID000005731': ['N02CC'],
 'CID000005732': ['N05CF'],
 'CID000003203': ['J05AG'],
 'CID000002140': ['V08AA', 'V08AA'],
 'CID000004485': ['C08CA'],
 'CID000060707': ['J01DH'],
 'CID000003117': ['N07BB', 'P03AA'],
 'CID000003114': ['C01BA'],
 'CID000004645': ['D06AA', 'G01AA', 'J01AA', 'S01AA'],
 'CID000038904': ['L01XA'],
 'CID000060147': ['G04CA'],
 'CID000004674': ['M05BA'],
 'CID000002522': ['D05AX'],
 'CID000002524': ['A11CC', 'D05AX'],
 'CID000104865': ['C02KX'],
 'CID004659568': ['N04BX'],
 'CID004659569': ['N04BX'],
 'CID000003062': ['C01AA', 'C01AA', 'C01AA', 'V03AB'],
 'CID000003066': ['N02CA'],
 'CID000154059': ['G04BD'],
 'CID000004889': ['C10AA'],
 'CID000004264': ['D06AX', 'R01AX'],
 'CID000000750': ['B03AA', 'B05CX'],
 'CID000002637': ['J01DC'],
 'CID000002631': ['J01DD'],
 'CID000160051': ['C10AC'],
 'CID000001986': ['S01EC'],
 'CID000003454': ['J05AB', 'J05AB', 'S01AD'],
 'CID000003690': ['L01AA'],
 'CID000151165': ['A04AD'],
 'CID000003696': ['N06AA', 'N06AA', 'N06AA'],
 'CID000003698': ['C01CE'],
 'CID000003929': ['J01XX'],
 'CID000004195': ['C01CA'],
 'CID000002949': ['G03XA'],
 'CID000004078': ['N05AC'],
 'CID000004900': ['A07EA', 'H02AB', 'H02AB'],
 'CID000005593': ['S01FA'],
 'CID000005452': ['N05AC'],
 'CID000004107': ['M03BA'],
 'CID000071329': ['C01BD'],
 'CID000005212': ['G04BE'],
 'CID000005210': ['A08AA'],
 'CID000005215': ['D06BA', 'J01EC'],
 'CID000004920': ['G03AC', 'G03DA', 'G03DA', 'G03DA', 'L02AB'],
 'CID000004927': ['D04AA', 'R06AD', 'R06AD'],
 'CID000008612': ['N01BA'],
 'CID000005430': ['D01AC', 'P02CA'],
 'CID000003324': ['J05AB', 'S01AD'],
 'CID000003325': ['A02BA'],
 'CID000124087': ['R06AX'],
 'CID000004856': ['M01AC', 'M02AA', 'S01BC'],
 'CID000005508': ['M01AB', 'M02AA'],
 'CID000005504': ['C04AB', 'M02AX'],
 'CID000005505': ['A10BB', 'V04CA'],
 'CID000054841': ['N06BA'],
 'CID000005726': ['J05AF'],
 'CID000005721': ['J05AH'],
 'CID000002182': ['L01XX'],
 'CID000002187': ['L02BG'],
 'CID000004993': ['P01BD'],
 'CID000003100': ['D04AA', 'D04AA', 'R06AA'],
 'CID000000861': ['H03AA'],
 'CID000003105': ['S01EA'],
 'CID000003108': ['B01AC', 'C01DX'],
 'CID000004675': ['M03AC'],
 'CID003468412': ['A07AA', 'D01AA', 'G01AA'],
 'CID000003075': ['C08DB'],
 'CID000068844': ['S01EC'],
 'CID000060714': ['V08CA'],
 'CID009571074': ['J01DD'],
 'CID000002583': ['C07AA', 'S01ED'],
 'CID000004451': ['J05AE'],
 'CID000002512': ['G02CB', 'N04BC'],
 'CID000002629': ['J01DD'],
 'CID000000137': ['L01XD'],
 'CID000041317': ['D05BB'],
 'CID000002622': ['J01DE'],
 'CID000062959': ['J01MA'],
 'CID000002995': ['N06AA'],
 'CID000002487': ['N02AF'],
 'CID000003467': ['D06AX', 'J01GB', 'S01AA', 'S02AA', 'S03AA'],
 'CID000003463': ['C10AB'],
 'CID000003461': ['L01BC'],
 'CID000003915': ['R01AC', 'S01GX'],
 'CID000003914': ['S01ED'],
 'CID000003661': ['A03BA',
  'A03BB',
  'N04AC',
  'N04AC',
  'S01FA',
  'S01FA',
  'A03BA'],
 'CID000039042': ['C10AB'],
 'CID000004062': ['N01BB'],
 'CID000004060': ['N03AB'],
 'CID000004064': ['N05BC'],
 'CID000002249': ['C07AB', 'C07AB'],
 'CID000152945': ['G04CB'],
 'CID000004112': ['L01BA', 'L04AX'],
 'CID011947681': ['C02DD'],
 'CID000002658': ['J01DC'],
 'CID005329102': ['L01XE'],
 'CID000004934': ['A03AB'],
 'CID000004935': ['S01HA'],
 'CID000004932': ['C01BC'],
 'CID000002655': ['J01DD'],
 'CID000039860': ['A04AD'],
 'CID000005538': ['D10AD', 'D10AD', 'L01XX', 'D10BA', 'D10AD', 'L01XX'],
 'CID000004845': ['R03AC', 'R03CC'],
 'CID000005533': ['N06AX'],
 'CID000005717': ['R03DC'],
 'CID000005719': ['N05CF'],
 'CID000005718': ['J05AF'],
 'CID000004201': ['C02DC', 'D11AX'],
 'CID000005155': ['J05AF'],
 'CID000005404': ['G01AG'],
 'CID000005403': ['R03AC', 'R03CC'],
 'CID000005402': ['D01AE', 'D01BA'],
 'CID000005401': ['G04CA'],
 'CID000005152': ['R03AC'],
 'CID000004666': ['L01CD'],
 'CID000002160': ['N06AA'],
 'CID000048041': ['C01BC'],
 'CID000000815': ['A07AA', 'J01GB', 'S01AA'],
 'CID000002441': ['N05BA'],
 'CID000060169': ['M03AC'],
 'CID000004595': ['A04AA'],
 'CID000060164': ['D10AD'],
 'CID000004599': ['A08AB'],
 'CID000002431': ['C01BD'],
 'CID000003000': ['D07AC', 'D07XC'],
 'CID000003003': ['A01AC',
  'C05AA',
  'D07AB',
  'D07XB',
  'D10AA',
  'H02AB',
  'R01AD',
  'S01BA',
  'S01CB',
  'S02BA',
  'S03BA'],
 'CID000003007': ['N06BA', 'N06BA'],
 'CID000438204': ['D06BA'],
 'CID000007029': ['A08AA'],
 'CID000123620': ['D07AC', 'D07XC', 'R01AD', 'R03BA'],
 'CID003002190': ['J01FA'],
 'CID000004449': ['N06AX'],
 'CID000002617': ['J01DB'],
 'CID000104758': ['L01BA'],
 'CID000003478': ['A10BB'],
 'CID000023897': ['N05AE'],
 'CID000163742': ['B01AX'],
 'CID000003475': ['A10BB'],
 'CID000003476': ['A10BB'],
 'CID000002891': ['B03BB', 'B03BA'],
 'CID000003676': ['C01BB',
  'C05AD',
  'D04AB',
  'N01BB',
  'R02AD',
  'S01HA',
  'S02DA',
  'A01AD'],
 'CID000003902': ['L02BG'],
 'CID000003675': ['N06AF'],
 'CID000003672': ['C01EB', 'G02CC', 'M01AE', 'M01AE', 'M02AA'],
 'CID000004058': ['N02AB'],
 'CID000004057': ['A03AB'],
 'CID000004054': ['N06DX'],
 'CID000004053': ['L01AA'],
 'CID000004052': ['M01AC'],
 'CID000003877': ['J05AF'],
 'CID000091270': ['C09AA'],
 'CID000003878': ['N03AX'],
 'CID000004121': ['C03AA'],
 'CID000065027': ['J05AE'],
 'CID000003494': ['A03AB'],
 'CID005311048': ['L01XA'],
 'CID000004409': ['M01AX'],
 'CID000016362': ['N05AG'],
 'CID000003869': ['C07AG'],
 'CID000004943': ['N01AX'],
 'CID000004946': ['C07AA'],
 'CID000005090': ['M01AH'],
 'CID000005525': ['C09AA'],
 'CID000005526': ['B02AA'],
 'CID000130881': ['C09CA'],
 'CID000009433': ['R03DA'],
 'CID000093860': ['L01XX'],
 'CID000003278': ['C03CC'],
 'CID000003279': ['J04AK'],
 'CID000072057': ['V08CA'],
 'CID000072054': ['G04BD'],
 'CID000005412': ['A01AB',
  'D06AA',
  'J01AA',
  'S01AA',
  'S02AA',
  'S03AA',
  'A01AB',
  'S01AA',
  'J01AA',
  'J01AA',
  'S01AA',
  'G01AA',
  'D06AA',
  'D06AA',
  'J01AA'],
 'CID000004614': ['M01AE'],
 'CID000004616': ['N05BA'],
 'CID000002477': ['N05BE'],
 'CID000002476': ['N02AE', 'N07BC'],
 'CID000002471': ['C03CA'],
 'CID000002274': ['J01DF'],
 'CID000001065': ['C01BA'],
 'CID000002519': ['N06BC', 'N02BE'],
 'CID000003928': ['J01FF'],
 'CID000004724': ['C07AA'],
 'CID000004723': ['N06BA'],
 'CID000003019': ['C02DA', 'V03AH'],
 'CID000000937': ['C04AC', 'C10AD'],
 'CID000003016': ['N05BA', 'N05BA'],
 'CID000122316': ['N04BD'],
 'CID000002609': ['J01DC'],
 'CID000005071': ['J05AC'],
 'CID000003702': ['C03BA'],
 'CID000150310': ['C03DA'],
 'CID000150311': ['C10AX'],
 'CID000004436': ['R01AA', 'S01GA', 'R01AB'],
 'CID000004100': ['S01EC'],
 'CID000004547': ['A10BX'],
 'CID000003648': ['N02AA'],
 'CID000004543': ['N06AA'],
 'CID000004542': ['G03AC', 'G03AD'],
 'CID000003647': ['C03AA'],
 'CID000060198': ['L02BG'],
 'CID000004043': ['S01BA'],
 'CID000004044': ['M01AG'],
 'CID000004046': ['P01BC'],
 'CID000003488': ['A10BB'],
 'CID000002720': ['C03AA', 'C03AA'],
 'CID000002726': ['N05AA'],
 'CID000004138': ['C02AB', 'C02AB'],
 'CID000002283': ['D06AX', 'R02AB', 'J01XX'],
 'CID000002284': ['M03BX'],
 'CID000005556': ['N05CD'],
 'CID000005396': ['L01CB'],
 'CID000005394': ['L01AX'],
 'CID000005391': ['N05CD'],
 'CID005311297': ['R03DC'],
 'CID000034633': ['C01BG'],
 'CID000005775': ['C04AB', 'V03AB'],
 'CID000003241': ['R06AX', 'S01GX'],
 'CID000667490': ['L01BB'],
 'CID000060835': ['N06AX'],
 'CID000060831': ['R03BB'],
 'CID000004603': ['J05AH'],
 'CID000004601': ['M03BC', 'N04AB'],
 'CID000004607': ['J01CF', 'J01CF', 'J01CF', 'J01CF'],
 'CID000004609': ['L01XA'],
 'CID000002462': ['A07EA', 'D07AC', 'R01AD', 'R03BA'],
 'CID001349907': ['H03BB'],
 'CID000000838': ['A01AD',
  'B02BC',
  'C01CA',
  'C01CA',
  'R01AA',
  'R03AA',
  'S01EA'],
 'CID000030623': ['V03AF'],
 'CID000002266': ['D10AX'],
 'CID000002267': ['R01AC', 'R06AX', 'S01GX'],
 'CID000002265': ['L04AX'],
 'CID000003393': ['N05CD'],
 'CID000003392': ['D07AC'],
 'CID000003394': ['M01AE', 'M02AA', 'S01BC'],
 'CID000003397': ['L02BB'],
 'CID000002269': ['J01FA', 'S01AA'],
 'CID000041781': ['C03CA', 'C03CA'],
 'CID000004739': ['A03AB'],
 'CID000004736': ['N02AD'],
 'CID000004737': ['N05CA'],
 'CID000060696': ['M03AC'],
 'CID000004730': ['J01CE', 'J01CE'],
 'CID000096312': ['L01BB'],
 'CID003085017': ['V03AE'],
 'CID000002673': ['J01DB'],
 'CID000002675': ['J01DD'],
 'CID000002676': ['C10AA'],
 'CID000002678': ['R06AE', 'R06AE'],
 'CID000003730': ['V08AB'],
 'CID000000232': ['B05XB'],
 'CID000003657': ['L01XX'],
 'CID000003652': ['P01BA'],
 'CID000003658': ['N05BB'],
 'CID000002708': ['L01AA'],
 'CID000000581': ['R05CB', 'S01XA', 'V03AB'],
 'CID000028112': ['N05AN', 'D11AX'],
 'CID000002818': ['N05AH'],
 'CID000068740': ['M05BA'],
 'CID000004091': ['A10BA', 'A10BD'],
 'CID000004095': ['N02AC', 'N07BC', 'R05DA'],
 'CID000005546': ['C03DB'],
 'CID000005544': ['A01AC',
  'D07AB',
  'D07XB',
  'H02AB',
  'R01AD',
  'R03BA',
  'S01BA',
  'C05AA'],
 'CID000040976': ['G03AC'],
 'CID000004197': ['C01CE'],
 'CID000004893': ['C02CA'],
 'CID000004891': ['P02BA'],
 'CID000031477': ['S01ED'],
 'CID000016231': ['C03DB'],
 'CID000004894': ['A07EA',
  'C05AA',
  'D07AA',
  'D07AA',
  'D07AC',
  'D07XA',
  'D10AA',
  'H02AB',
  'H02AB',
  'R01AD',
  'S01BA',
  'S01CB',
  'S02BA',
  'S03BA',
  'H02AB'],
 'CID000002381': ['N04AA'],
 'CID000003261': ['N05CD'],
 'CID000003251': ['N02CA', 'N02CA'],
 'CID000003255': ['D10AF', 'J01FA', 'S01AA'],
 'CID000050614': ['J01DC'],
 'CID000004635': ['N02AA'],
 'CID000004634': ['G04BD'],
 'CID000004428': ['N07BB'],
 'CID005282226': ['S01EE'],
 'CID000054454': ['C10AA'],
 'CID000057469': ['D06BB'],
 'CID000003382': ['C05AA', 'D07AC'],
 'CID000003381': ['C05AA', 'D07AC', 'S01BA', 'S02BA'],
 'CID000003387': ['G03BA'],
 'CID000003384': ['C05AA', 'D07AB', 'D07XB', 'D10AA', 'S01BA', 'S01CB'],
 'CID000001046': ['J04AK'],
 'CID000003739': ['V08AC'],
 'CID000056959': ['C01EB'],
 'CID000000085': ['A16AA'],
 'CID000003032': ['M01AB', 'M02AA', 'S01BC', 'D11AX'],
 'CID000060753': ['C01BD'],
 'CID000060754': ['V08CA'],
 'CID000002662': ['L01XX', 'M01AH'],
 'CID000002666': ['J01DB'],
 'CID000004419': ['N02AF'],
 'CID006323497': ['J04AB'],
 'CID000003724': ['V08AB'],
 'CID000054547': ['J01DD'],
 'CID000002719': ['P01BA', 'P01BA'],
 'CID000002712': ['N05BA'],
 'CID000000596': ['L01BC'],
 'CID000000772': ['B01AB', 'C05BA', 'C05BA', 'S01XA', 'S01XA', 'B01AB'],
 'CID000003827': ['R06AX', 'S01GX'],
 'CID000003826': ['M01AB', 'S01BC'],
 'CID000003825': ['M01AE', 'M01AE', 'M02AA'],
 'CID000003823': ['D01AC', 'G01AF', 'J02AB'],
 'CID000003821': ['N01AX', 'N01AX'],
 'CID000004140': ['G02AB'],
 'CID000002803': ['C02AC', 'N02CX', 'S01EA', 'S01EA'],
 'CID000002806': ['B01AC'],
 'CID000062867': ['N05AC'],
 'CID000004158': ['N06BA'],
 'CID000004159': ['D07AA', 'D07AC', 'D10AA', 'H02AB'],
 'CID000115237': ['N05AX'],
 'CID000013342': ['L01CA'],
 'CID000004259': ['J01MA', 'S01AE'],
 'CID004479097': ['B03BA', 'V03AB'],
 'CID000004086': ['R03CB', 'R03AB'],
 'CID000005578': ['J01EA'],
 'CID000005572': ['N04AA'],
 'CID000005379': ['J01MA', 'S01AE'],
 'CID000005376': ['L02BA'],
 'CID000005596': ['G04BD'],
 'CID000005591': ['A10BG'],
 'CID000060815': ['N01AH'],
 'CID000004976': ['N06AA'],
 'CID000002443': ['G02CB', 'N04BC'],
 'CID005353894': ['V03AB'],
 'CID000005625': ['J05AG'],
 'CID000004623': ['D01AC', 'G01AF'],
 'CID000002244': ['A01AD', 'B01AC', 'N02BA'],
 'CID000047319': ['M03AC', 'M03AC'],
 'CID000170361': ['N07BA'],
 'CID000003375': ['C05AA', 'D07AC'],
 'CID000087177': ['A06AD'],
 'CID000037393': ['P01BX'],
 'CID000041693': ['N01AH'],
 'CID000005978': ['L01CA'],
 'CID000060787': ['J05AE'],
 'CID000002656': ['J01DD'],
 'CID000002650': ['J01DD'],
 'CID000003759': ['N06AF'],
 'CID000004594': ['A02BC', 'A02BC'],
 'CID000003750': ['L01XX'],
 'CID000065999': ['C09CA'],
 'CID000005193': ['N05CA'],
 'CID000157922': ['L01XD'],
 'CID000002951': ['M03CA'],
 'CID000003637': ['C02DB', 'C02DB'],
 'CID000003639': ['C03AA'],
 'CID000054374': ['H01CB'],
 'CID000002727': ['A10BB'],
 'CID000002725': ['R06AB', 'R06AB'],
 'CID000003767': ['J04AC'],
 'CID000004915': ['L01XB'],
 'CID000005582': ['P01AX'],
 'CID000004189': ['A01AB', 'A07AC', 'D01AC', 'G01AF', 'J02AB', 'S02AA'],
 'CID000003958': ['N05BA'],
 'CID000000143': ['V03AF'],
 'CID000036339': ['N01AX'],
 'CID000004168': ['A03FA'],
 'CID000004163': ['N02CA'],
 'CID000004160': ['G03BA', 'G03EK'],
 'CID000002812': ['A01AB', 'D01AC', 'G01AF'],
 'CID000002907': ['L01AA', 'L01DB'],
 'CID000002905': ['S01FA'],
 'CID006398970': ['J01DD'],
 'CID000002019': ['L01DA'],
 'CID000005291': ['L01XE'],
 'CID000005297': ['A07AA', 'J01GA', 'S01AA'],
 'CID000002913': ['R06AX'],
 'CID000005566': ['N05AB'],
 'CID000002083': ['R03CC', 'R03AC'],
 'CID000158440': ['V08CA'],
 'CID000005584': ['N06AA'],
 'CID000016850': ['S01JA'],
 'CID000002123': ['L01XX'],
 'CID000034312': ['N03AF'],
 'CID000002232': ['B01AE'],
 'CID000005035': ['G03XC'],
 'CID000039507': ['H02AB', 'S01BA'],
 'CID000005746': ['L01DC'],
 'CID000005038': ['C09AA'],
 'CID000005039': ['A02BA', 'A02BA'],
 'CID000004768': ['C04AX'],
 'CID000002344': ['N04AC'],
 'CID000002349': ['J01CE', 'S01AA', 'J01CE', 'J01CE'],
 'CID000003291': ['N03AD'],
 'CID000003715': ['M01AB', 'C01EB'],
 'CID000072467': ['L01DC'],
 'CID000050294': ['R01AC', 'R03BC', 'S01GX'],
 'CID000002646': ['J01DC'],
 'CID000003749': ['C09CA'],
 'CID000003746': ['R01AX', 'R03BB'],
 'CID000002610': ['J01DB'],
 'CID000004440': ['N02CC'],
 'CID000002732': ['C03BA'],
 'CID000064147': ['J05AB'],
 'CID000004509': ['J01XE'],
 'CID000444033': ['R03BA'],
 'CID000004506': ['N05CD', 'N05CD'],
 'CID005311039': ['J02AX'],
 'CID000003519': ['C02AC'],
 'CID000003518': ['C02CC', 'S01EX'],
 'CID000004211': ['L01XX'],
 'CID000003512': ['D01AA', 'D01BA'],
 'CID000003510': ['A04AA'],
 'CID000000159': ['B01AC'],
 'CID000000158': ['G02AD'],
 'CID000004178': ['C01BB'],
 'CID005481350': ['J05AF'],
 'CID000001935': ['N06AA', 'N06DA'],
 'CID000004170': ['C03BA'],
 'CID000004171': ['C07AB', 'C07AB'],
 'CID000004173': ['A01AB', 'D06BX', 'G01AF', 'J01XD', 'P01AB'],
 'CID000027686': ['R01AC', 'A07EB', 'S01GX', 'R03BC', 'D11AH'],
 'CID000003226': ['N01AB'],
 'CID000150610': ['J01DH'],
 'CID000071158': ['N07BB'],
 'CID000657298': ['H03BA'],
 'CID000006691': ['B01AA'],
 'CID005311181': ['B01AC'],
 'CID005381226': ['J04AB'],
 'CID000036811': ['C01CA'],
 'CID000004196': ['G03XB'],
 'CID000005359': ['M01AE'],
 'CID000004192': ['N05CD'],
 'CID000005352': ['M01AB'],
 'CID000060184': ['C09AA'],
 'CID000002133': ['D07AC'],
 'CID000002130': ['N04BB'],
 'CID000002131': ['N07AA'],
 'CID000060879': ['C09CA'],
 'CID000060871': ['J05AF'],
 'CID000004991': ['N07AA'],
 'CID000005645': ['A05AA'],
 'CID000005647': ['J05AB'],
 'CID000002171': ['J01CA'],
 'CID000003355': ['C01BC'],
 'CID000003354': ['G04BD'],
 'CID000051263': ['N01AH'],
 'CID000003350': ['D11AX', 'G04CB'],
 'CID000005002': ['N05AH'],
 'CID000005005': ['C09AA'],
 'CID000004771': ['A08AA'],
 'CID005353980': ['A07EC'],
 'CID000000942': ['N07BA', 'A11HA', 'C04AC', 'C10AD'],
 'CID006447131': ['D11AH'],
 'CID000003292': ['N03AB'],
 'CID000003779': ['C01CA', 'D08AX'],
 'CID000110635': ['G04BE'],
 'CID000110634': ['G04BE'],
 'CID000041744': ['L01DB'],
 'CID000477468': ['J02AX'],
 'CID000002749': ['D01AE', 'G01AX'],
 'CID000002585': ['C07AG'],
 'CID000145068': ['R07AX'],
 'CID000004510': ['C01DA'],
 'CID000048175': ['D07AC'],
 'CID000004205': ['N06AX'],
 'CID000004200': ['A01AB', 'J01AA'],
 'CID000005381': ['D05AX'],
 'CID005361912': ['J04AB'],
 'CID000002520': ['C08DA'],
 'CID000039765': ['M03AC'],
 'CID000003403': ['C10AA'],
 'CID000042113': ['N01AB'],
 'CID000005344': ['J01EB', 'S01AB'],
 'CID000005342': ['M04AB'],
 'CID000004834': ['J01CA'],
 'CID000123606': ['N02CC'],
 'CID000060865': ['S01GX', 'R01AC'],
 'CID000005650': ['C09CA'],
 'CID000005651': ['A07AA', 'J01XA'],
 'CID006435110': ['P02CF'],
 'CID000002216': ['S01EA'],
 'CID000002215': ['G04BE', 'N04BC'],
 'CID000003348': ['R06AX'],
 'CID000003342': ['M01AE'],
 'CID000003340': ['C01CA'],
 'CID000006058': ['A16AA'],
 'CID000004748': ['N05AB'],
 'CID000004740': ['C04AD'],
 'CID000000951': ['C01CA'],
 'CID000002366': ['N07CA'],
 'CID000002369': ['C07AB', 'S01ED'],
 'CID000025419': ['M05BA'],
 'CID000006476': ['N03AD'],
 'CID000003763': ['N01AB'],
 'CID000059708': ['N03AX'],
 'CID000003161': ['A01AB', 'J01AA'],
 'CID000003168': ['N05AD'],
 'CID000000888': ['A12CC',
  'B05XA',
  'A06AD',
  'B05XA',
  'A06AD',
  'A02AA',
  'A12CC',
  'A02AA',
  'A06AD',
  'A12CC',
  'A12CC',
  'A12CC',
  'B05CB',
  'A12CC',
  'G04BX',
  'A12CC',
  'A12CC',
  'A02AA',
  'A06AD',
  'A02AA',
  'A12CC',
  'A02AA',
  'A06AD',
  'C10AX',
  'A12CC',
  'A12CC',
  'D11AX',
  'V04CC',
  'B05XA'],
 'CID000041774': ['A10BF'],
 'CID000002733': ['M03BB'],
 'CID000000401': ['J04AB'],
 'CID000002751': ['C09AA'],
 'CID000002756': ['A02BA'],
 'CID005281007': ['L01AX'],
 'CID000005358': ['N02CC'],
 'CID000444013': ['V08CA'],
 'CID000004463': ['J05AG'],
 'CID000004236': ['N06BA'],
 'CID000104741': ['L02BA'],
 'CID000003883': ['A02BC'],
 'CID000003405': ['B03BB'],
 'CID000003406': ['V03AB'],
 'CID000002978': ['A04AD'],
 'CID000002973': ['V03AC'],
 'CID000002250': ['C10AA'],
 'CID002761171': ['J04AD'],
 'CID000002021': ['J01XX'],
 'CID000002022': ['D06BB', 'J05AB', 'S01AD', 'J05AB'],
 'CID003000502': ['J04AB'],
 'CID000003385': ['L01BC'],
 'CID000002118': ['N05BA'],
 'CID000004828': ['C07AA', 'C07AA', 'C07AA'],
 'CID000004829': ['A10BG'],
 'CID000001125': ['A16AX'],
 'CID000123631': ['L01XE'],
 'CID000004919': ['N04AA'],
 'CID000060852': ['M05BA'],

In [210]:
act2cid = {}
for curr_atc in tqdm(list_atc4_exist):
    
    unique_cid = []
    for cid, list_atc in cid2atc_dic.items():
        if curr_atc in list_atc:
            unique_cid.append(cid)
    if len(unique_cid) != 0:
        act2cid[curr_atc] = unique_cid  # each exist act4 code may have multiple cid codes
    
act2cid

  0%|          | 0/346 [00:00<?, ?it/s]

{'C01BA': ['CID000004914', 'CID000004913', 'CID000003114', 'CID000001065'],
 'N06BA': ['CID000054841',
  'CID000003007',
  'CID000004723',
  'CID000004158',
  'CID000004236',
  'CID000001206'],
 'N06AX': ['CID000005533',
  'CID000004449',
  'CID000060835',
  'CID000004205',
  'CID000125017',
  'CID000001148'],
 'N05AH': ['CID000002818', 'CID000005002', 'CID000003964'],
 'G03XC': ['CID000005035'],
 'B01AC': ['CID000003108',
  'CID000002806',
  'CID000002244',
  'CID000000159',
  'CID005311181',
  'CID000005486',
  'CID000005472',
  'CID000054786'],
 'A01AC': ['CID000003003', 'CID000005544'],
 'L01XE': ['CID000176870',
  'CID005329102',
  'CID000005291',
  'CID000123631',
  'CID003062316'],
 'J01CE': ['CID000004914', 'CID000004730', 'CID000002349'],
 'L01XX': ['CID000018140',
  'CID000005515',
  'CID000002182',
  'CID000005538',
  'CID000093860',
  'CID000003657',
  'CID000002662',
  'CID000003750',
  'CID000002123',
  'CID000004211',
  'CID000082146',
  'CID000014888',
  'CID000002179'],
 'J05AF': ['CID000005726',
  'CID000005718',
  'CID000005155',
  'CID000003877',
  'CID005481350',
  'CID000060871',
  'CID000001971',
  'CID000003043'],
 'L04AA': ['CID000003899', 'CID000005040'],
 'J01DF': ['CID000002274'],
 'J01GB': ['CID000002142',
  'CID000003467',
  'CID000000815',
  'CID000005496',
  'CID000504578'],
 'J05AE': ['CID000131536',
  'CID000003706',
  'CID000213039',
  'CID000004451',
  'CID000065027',
  'CID000060787',
  'CID000005076',
  'CID000002177'],
 'C10AA': ['CID004475485',
  'CID000004889',
  'CID000002676',
  'CID000054454',
  'CID000003403',
  'CID000002250',
  'CID000003962'],
 'J05AB': ['CID000003454',
  'CID000003324',
  'CID000064147',
  'CID000005647',
  'CID000002022',
  'CID000005064',
  'CID000060613'],
 'N03AE': ['CID000002802'],
 'D01AE': ['CID000005402', 'CID000002749', 'CID000003366'],
 'A11CC': ['CID000002524'],
 'M05BA': ['CID000003305',
  'CID000002088',
  'CID000004674',
  'CID000068740',
  'CID000025419',
  'CID000060852',
  'CID000005245',
  'CID000060937'],
 'C03CA': ['CID000003440', 'CID000002471', 'CID000041781'],
 'J05AH': ['CID000005721', 'CID000004603'],
 'L01BC': ['CID000003461', 'CID000000596', 'CID000003385'],
 'N04BX': ['CID004659568', 'CID004659569'],
 'S01EC': ['CID000001986', 'CID000068844', 'CID000004100'],
 'H03BA': ['CID000657298'],
 'A01AB': ['CID000005412',
  'CID000004189',
  'CID000002812',
  'CID000004173',
  'CID000004200',
  'CID000003161',
  'CID000001972',
  'CID000002713',
  'CID000504578'],
 'D11AX': ['CID000004201',
  'CID000028112',
  'CID000003032',
  'CID000003350',
  'CID000000888'],
 'C03CC': ['CID000003278'],
 'R03DC': ['CID000005717', 'CID005311297'],
 'C01EB': ['CID000003672', 'CID000056959', 'CID000003715', 'CID000000191'],
 'N02CC': ['CID000077992',
  'CID000077993',
  'CID000005731',
  'CID000004440',
  'CID000123606',
  'CID000005358',
  'CID000005078'],
 'A04AD': ['CID000151165', 'CID000039860', 'CID000002978'],
 'C09CA': ['CID000130881',
  'CID000065999',
  'CID000003749',
  'CID000060879',
  'CID000005650',
  'CID000003961',
  'CID000002541'],
 'A02BA': ['CID000003325', 'CID000005039', 'CID000002756', 'CID000004513'],
 'N04AC': ['CID000003661', 'CID000002344'],
 'J01DH': ['CID000060707', 'CID000150610'],
 'C03AA': ['CID000004870',
  'CID000004121',
  'CID000003647',
  'CID000002720',
  'CID000003639',
  'CID000002315'],
 'J02AX': ['CID005311039', 'CID000477468', 'CID000003366'],
 'L01AA': ['CID000003690', 'CID000004053', 'CID000002708', 'CID000002907'],
 'B01AX': ['CID000163742'],
 'N05AB': ['CID000004917', 'CID000005566', 'CID000004748', 'CID000003372'],
 'C03DB': ['CID000005546', 'CID000016231'],
 'C07AG': ['CID000003869', 'CID000002585'],
 'L01BB': ['CID000667490',
  'CID000096312',
  'CID000001546',
  'CID000003367',
  'CID005473385'],
 'B01AE': ['CID000002232'],
 'N06AF': ['CID000003675', 'CID000003759'],
 'N04BC': ['CID000002512', 'CID000002443', 'CID000002215', 'CID000004253'],
 'H03AA': ['CID000000861', 'CID000000853'],
 'P02CA': ['CID000002082', 'CID000005430', 'CID000004030'],
 'D04AA': ['CID000004927', 'CID000003100', 'CID000002781'],
 'N02AA': ['CID000003648', 'CID000004635', 'CID000004253'],
 'N05CA': ['CID000004737', 'CID000005193', 'CID000009034'],
 'N05BA': ['CID000002441',
  'CID000004616',
  'CID000003016',
  'CID000002712',
  'CID000003958',
  'CID000002118'],
 'A02BC': ['CID000004594', 'CID000003883'],
 'N05CF': ['CID000005735', 'CID000005732', 'CID000005719'],
 'C07AB': ['CID000071301',
  'CID000059768',
  'CID000002249',
  'CID000004171',
  'CID000002369',
  'CID000001978',
  'CID000002405'],
 'J01AA': ['CID000004645',
  'CID000005412',
  'CID000004200',
  'CID000003161',
  'CID000002983',
  'CID005282044'],
 'D07AA': ['CID000004894', 'CID000004159'],
 'G03AC': ['CID000004536',
  'CID000019090',
  'CID000004920',
  'CID000004542',
  'CID000040976'],
 'D06AX': ['CID000002142',
  'CID006436173',
  'CID000004264',
  'CID000003467',
  'CID000002283',
  'CID000504578',
  'CID000000298'],
 'C10AC': ['CID000062816', 'CID000160051'],
 'A10BB': ['CID000005503',
  'CID000005505',
  'CID000003478',
  'CID000003475',
  'CID000003476',
  'CID000003488',
  'CID000002727'],
 'G03BA': ['CID000005408', 'CID000003387', 'CID000004160'],
 'D10AF': ['CID000003255', 'CID000002786', 'CID000000298'],
 'G02AD': ['CID000000158'],
 'J05AG': ['CID000003203', 'CID000005625', 'CID000004463'],
 'C01BD': ['CID000002156', 'CID000071329', 'CID000002431', 'CID000060753'],
 'G04BD': ['CID000005512',
  'CID000154059',
  'CID000072054',
  'CID000004634',
  'CID000005596',
  'CID000003354'],
 'L01DB': ['CID000003685',
  'CID000002907',
  'CID000041744',
  'CID000004212',
  'CID000002958'],
 'J01XX': ['CID000003929', 'CID000002283', 'CID000002021', 'CID000003417'],
 'L02BG': ['CID000002145', 'CID000002187', 'CID000003902', 'CID000060198'],
 'A07EC': ['CID005353980', 'CID000004075', 'CID005362070'],
 'B02AA': ['CID000005526'],
 'J04AB': ['CID006323497',
  'CID005381226',
  'CID005361912',
  'CID000000401',
  'CID003000502'],
 'S01EE': ['CID005282226', 'CID000003890', 'CID005311027'],
 'L01AD': ['CID000005300', 'CID000002578', 'CID000003950'],
 'L01XA': ['CID000038904', 'CID005311048', 'CID000004609'],
 'R05CB': ['CID000000581'],
 'J01CF': ['CID000004607', 'CID000003040'],
 'J01CA': ['CID000002559', 'CID000002171', 'CID000004834', 'CID000002173'],
 'M01AB': ['CID000003308',
  'CID000005508',
  'CID000003032',
  'CID000003826',
  'CID000003715',
  'CID000005352'],
 'P03AC': ['CID000040159'],
 'C01CA': ['CID000004195',
  'CID000000838',
  'CID000036811',
  'CID000003779',
  'CID000003340',
  'CID000000951',
  'CID000000681'],
 'L01XD': ['CID000000137', 'CID000157922'],
 'P01BA': ['CID000004908', 'CID000003652', 'CID000002719'],
 'C03DA': ['CID000150310', 'CID000005267'],
 'A02BB': ['CID004183806'],
 'A10BF': ['CID000041774', 'CID000051577'],
 'D07AB': ['CID004630253', 'CID000003003', 'CID000005544', 'CID000003384'],
 'J01MA': ['CID000072938',
  'CID000062959',
  'CID000004259',
  'CID000005379',
  'CID000004539',
  'CID000003948'],
 'C08CA': ['CID000004497',
  'CID000004473',
  'CID000004485',
  'CID000003333',
  'CID000002162',
  'CID000003784'],
 'A10BG': ['CID000005591', 'CID000004829', 'CID000077999'],
 'N06AB': ['CID000005203'],
 'A03BA': ['CID000003661'],
 'C02AC': ['CID000002803', 'CID000003519'],
 'G03DA': ['CID000004920'],
 'R03DA': ['CID000002153', 'CID000009433'],
 'R01AC': ['CID000003915',
  'CID000002267',
  'CID000050294',
  'CID000027686',
  'CID000060865'],
 'N03AX': ['CID000005734', 'CID000003878', 'CID000059708'],
 'M01CC': ['CID000004727'],
 'C09AA': ['CID000002550',
  'CID000003937',
  'CID000091270',
  'CID000005525',
  'CID000005038',
  'CID000060184',
  'CID000005005',
  'CID000002751',
  'CID000003419',
  'CID000003957',
  'CID000003222',
  'CID000002311'],
 'N02BE': ['CID000002519'],
 'A01AD': ['CID000003676', 'CID000000838', 'CID000002244'],
 'V03AB': ['CID000003062',
  'CID000005775',
  'CID000000581',
  'CID004479097',
  'CID005353894',
  'CID000003406',
  'CID000003373',
  'CID000004425'],
 'C07AA': ['CID000002583',
  'CID000004946',
  'CID000004724',
  'CID000004828',
  'CID000004411',
  'CID000005253',
  'CID000005478'],
 'G03CA': ['CID000000450'],
 'C02CA': ['CID000004893', 'CID000003157'],
 'J02AC': ['CID000003793', 'CID000003365'],
 'D01AC': ['CID000005430',
  'CID000003823',
  'CID000004623',
  'CID000004189',
  'CID000002812',
  'CID000003365'],
 'N05AE': ['CID000023897', 'CID000060854'],
 'N07AA': ['CID000002131', 'CID000004991'],
 'A07EA': ['CID000004900', 'CID000002462', 'CID000004894', 'CID000002308'],
 'V03AE': ['CID003085017'],
 'N03AF': ['CID000002554', 'CID000034312'],
 'N02AE': ['CID000002476'],
 'D07AC': ['CID000052421',
  'CID000003000',
  'CID000123620',
  'CID000002462',
  'CID000003392',
  'CID000004894',
  'CID000003382',
  'CID000003381',
  'CID000004159',
  'CID000003375',
  'CID000002133',
  'CID000048175',
  'CID000002308'],
 'N05AD': ['CID000003168', 'CID000003559'],
 'C01BB': ['CID000003676', 'CID000004178'],
 'N02AB': ['CID000004058'],
 'N07BC': ['CID000002476', 'CID000004095'],
 'L04AX': ['CID000004112', 'CID000002265'],
 'N05CD': ['CID000005556',
  'CID000005391',
  'CID000003393',
  'CID000003261',
  'CID000004506',
  'CID000004192'],
 'R05DA': ['CID000004095', 'CID000004253'],
 'C01AA': ['CID000003062'],
 'A06AD': ['CID000087177', 'CID000000888', 'CID000000453'],
 'A07DA': ['CID000003954'],
 'A03FA': ['CID000004168', 'CID000003151', 'CID000002769'],
 'N03AA': ['CID000004909'],
 'A03AB': ['CID000004934', 'CID000004057', 'CID000003494', 'CID000004739'],
 'B01AA': ['CID000006691'],
 'D10AD': ['CID000005538', 'CID000060164'],
 'G01AG': ['CID000005404'],
 'R01AA': ['CID000004436', 'CID000000838'],
 'S01FA': ['CID000005593', 'CID000003661', 'CID000002905'],
 'S01EA': ['CID000002435',
  'CID000003105',
  'CID000000838',
  'CID000002803',
  'CID000002216'],
 'C05AD': ['CID000004914', 'CID000003676'],
 'R06AE': ['CID000002678'],
 'J01FA': ['CID000054688', 'CID003002190', 'CID000002269', 'CID000003255'],
 'G04BE': ['CID000005212',
  'CID000110635',
  'CID000110634',
  'CID000002215',
  'CID000004253'],
 'N03AB': ['CID000056339', 'CID000001775', 'CID000004060', 'CID000003292'],
 'N03AD': ['CID000003291', 'CID000006476'],
 'C01DA': ['CID000004510', 'CID000003780', 'CID000027661'],
 'D05AX': ['CID000002522', 'CID000002524', 'CID000005381'],
 'B01AB': ['CID000000772'],
 'N02AF': ['CID000002487', 'CID000004419'],
 'N03AG': ['CID000003121', 'CID000005466', 'CID000005665'],
 'N05CM': ['CID000060612'],
 'N01AX': ['CID000004943', 'CID000003821', 'CID000036339'],
 'C02DD': ['CID011947681'],
 'B05XA': ['CID000004873', 'CID000008953', 'CID000000888'],
 'L02AE': ['CID000047725'],
 'M03AC': ['CID000004675',
  'CID000060169',
  'CID000060696',
  'CID000047319',
  'CID000039765',
  'CID000047320',
  'CID000104803'],
 'B05CX': ['CID000000750', 'CID000000453'],
 'C10AB': ['CID000003339', 'CID000003463', 'CID000039042'],
 'B05CB': ['CID000008953', 'CID000000888'],
 'A12BA': ['CID000004873'],
 'H01BA': ['CID000027991'],
 'G02CB': ['CID000002512', 'CID000002443'],
 'G02AB': ['CID000004140'],
 'H01CB': ['CID000054374'],
 'N06AA': ['CID000004011',
  'CID000003696',
  'CID000002995',
  'CID000002160',
  'CID000004543',
  'CID000004976',
  'CID000005584',
  'CID000001935',
  'CID000003158',
  'CID000002170'],
 'A05AA': ['CID000005645'],
 'N06DA': ['CID000003449', 'CID000001935'],
 'A10BX': ['CID000443871', 'CID000004547'],
 'V03AC': ['CID000002973'],
 'C09XA': ['CID005493444'],
 'R06AX': ['CID000124087',
  'CID000003241',
  'CID000002267',
  'CID000003827',
  'CID000002913',
  'CID000003348',
  'CID000003957'],
 'L01AX': ['CID000005394', 'CID005281007'],
 'R03AC': ['CID000004845',
  'CID000005403',
  'CID000005152',
  'CID000002083',
  'CID000003410'],
 'P02BA': ['CID000004891'],
 'N06BC': ['CID000002519'],
 'A10BA': ['CID000004091'],
 'A04AA': ['CID000148211', 'CID000004595', 'CID000003510', 'CID000003148'],
 'A02BX': ['CID006398525'],
 'D06BB': ['CID000057469', 'CID000002022'],
 'J01EC': ['CID000005215'],
 'C05AA': ['CID000003003',
  'CID000005544',
  'CID000004894',
  'CID000003382',
  'CID000003381',
  'CID000003384',
  'CID000003375'],
 'M01AC': ['CID000004856', 'CID000004052'],
 'L02BA': ['CID000005516', 'CID000005376', 'CID000104741'],
 'J05AC': ['CID000005071'],
 'D06AA': ['CID000004645', 'CID000005412', 'CID000002983'],
 'H02AA': ['CID000031378'],
 'G04CA': ['CID000002092', 'CID000060147', 'CID000005401'],
 'A02AA': ['CID000000888'],
 'N04BB': ['CID000002130'],
 'N07BA': ['CID000170361', 'CID000000942'],
 'M03BA': ['CID000004107'],
 'J01DB': ['CID000002617', 'CID000002673', 'CID000002666', 'CID000002610'],
 'D05BB': ['CID000041317'],
 'J01XE': ['CID000004509'],
 'M03CA': ['CID000002951'],
 'A07AA': ['CID006436173',
  'CID003468412',
  'CID000000815',
  'CID000005297',
  'CID000005651',
  'CID000004689',
  'CID000001972',
  'CID000504578'],
 'D07AD': ['CID000032797'],
 'C08DA': ['CID000002520'],
 'L02BB': ['CID000004493', 'CID000003397', 'CID000002375'],
 'N05BE': ['CID000002477'],
 'P01BD': ['CID000004993'],
 'J01DC': ['CID000002637',
  'CID000002658',
  'CID000002609',
  'CID000050614',
  'CID000002646'],
 'P01AX': ['CID000005582', 'CID000074989'],
 'G04BX': ['CID000000888'],
 'B03BB': ['CID000002891', 'CID000003405'],
 'C02DB': ['CID000003637'],
 'N05BB': ['CID000003658'],
 'B03AA': ['CID000000750'],
 'H03BB': ['CID001349907'],
 'A14AA': ['CID000005878'],
 'N01BB': ['CID000071273', 'CID000004062', 'CID000003676', 'CID000002474'],
 'J05AD': ['CID000003414'],
 'V04CC': ['CID000000888'],
 'J01DD': ['CID000002631',
  'CID009571074',
  'CID000002629',
  'CID000002655',
  'CID000002675',
  'CID000054547',
  'CID000002656',
  'CID000002650',
  'CID006398970'],
 'C01CE': ['CID000003698', 'CID000004197'],
 'M04AB': ['CID000004911', 'CID000005342'],
 'J01EA': ['CID000005578'],
 'C02DC': ['CID000004201'],
 'N01AH': ['CID000060815', 'CID000041693', 'CID000051263'],
 'L01CD': ['CID000004666', 'CID000003143'],
 'M03AB': ['CID000005314'],
 'D08AX': ['CID000003779'],
 'N06DX': ['CID000004054'],
 'D11AH': ['CID000027686', 'CID006447131'],
 'R01AX': ['CID000004909', 'CID000004264', 'CID000003746'],
 'B03BA': ['CID000002891', 'CID004479097'],
 'P03AB': ['CID000000727'],
 'A03AA': ['CID000003042'],
 'N07BB': ['CID000003117', 'CID000004428', 'CID000071158'],
 'C02DA': ['CID000003019'],
 'N05AA': ['CID000002726'],
 'L01DC': ['CID000005746', 'CID000072467'],
 'L01CA': ['CID000013342', 'CID000005978', 'CID000005672'],
 'L01CB': ['CID000005396', 'CID000003310'],
 'N05AC': ['CID000004078', 'CID000005452', 'CID000062867'],
 'N02BA': ['CID000003059', 'CID000002244'],
 'M03BX': ['CID000002284', 'CID000005487', 'CID000002895'],
 'G02CC': ['CID000003672'],
 'N05AX': ['CID000115237'],
 'N07AX': ['CID000004819'],
 'D06BA': ['CID000005215', 'CID000438204'],
 'M01AE': ['CID000003672',
  'CID000004614',
  'CID000003394',
  'CID000003825',
  'CID000005359',
  'CID000003342'],
 'P01BC': ['CID000004046'],
 'A07EB': ['CID000027686'],
 'S01ED': ['CID000002583',
  'CID000003914',
  'CID000031477',
  'CID000002369',
  'CID000005478'],
 'R02AB': ['CID000002283', 'CID000504578'],
 'N04BD': ['CID000122316'],
 'M01AX': ['CID000004409'],
 'D10AX': ['CID000002266', 'CID000004253', 'CID000002955'],
 'N07AB': ['CID000002551', 'CID000002370'],
 'A16AA': ['CID000000085', 'CID000006058'],
 'C03BA': ['CID000003702', 'CID000002732', 'CID000004170'],
 'J04AC': ['CID000003767'],
 'N04AA': ['CID000002381', 'CID000005572', 'CID000004919'],
 'R06AB': ['CID000002725'],
 'C02AB': ['CID000004138'],
 'M04AA': ['CID000083786'],
 'N05AF': ['CID000005454'],
 'L01BA': ['CID000004112', 'CID000104758', 'CID000060843'],
 'J04AK': ['CID000003279', 'CID000001046'],
 'B02BC': ['CID000000838'],
 'C01BC': ['CID000004932', 'CID000048041', 'CID000003355'],
 'L01XB': ['CID000004915'],
 'C04AB': ['CID000005504', 'CID000005775'],
 'L01AC': ['CID000005453'],
 'V03AF': ['CID000002141', 'CID000030623', 'CID000000143'],
 'H05BX': ['CID005281104', 'CID000156419'],
 'N05AG': ['CID000016362'],
 'L01AB': ['CID000002478'],
 'S01EB': ['CID000002551', 'CID000000187', 'CID000004819', 'CID000010548'],
 'J01DE': ['CID000002622'],
 'S01HA': ['CID000004914', 'CID000004935', 'CID000003676'],
 'S01AD': ['CID000003454', 'CID000003324', 'CID000002022', 'CID000006256'],
 'R06AA': ['CID000003100', 'CID000002564', 'CID000002781'],
 'A11HA': ['CID000000942'],
 'A06AX': ['CID005487301'],
 'C04AX': ['CID000004768'],
 'C01DX': ['CID000003108'],
 'C10AX': ['CID000150311', 'CID000000888', 'CID000000853']}

In [207]:
df_drug_ndc_feat_ndc_real['list_cid'] = df_drug_ndc_feat_ndc_real['ATC4'].map(act2cid)
df_drug_ndc_feat_ndc_real

,NDC,RXCUI,idx,ATC4,list_cid
0,2.050101e+06,207882.0,173,NaN,NaN
1,2.140701e+06,853004.0,174,C01BA,"[CID000004914, CID000004913, CID000003114, CID..."
2,2.144401e+06,208815.0,175,NaN,NaN
3,2.202402e+06,313009.0,176,A12CA,NaN
4,2.322930e+06,352320.0,177,N06BA,"[CID000054841, CID000003007, CID000004723, CID..."
...,...,...,...,...,...
4096,7.431200e+10,309604.0,4287,NaN,NaN
4097,7.431200e+10,313896.0,4288,NaN,NaN
4098,7.811200e+10,1101849.0,4289,NaN,NaN
4099,7.951105e+10,669319.0,4290,NaN,NaN
4100,8.770108e+10,1049906.0,4292,D04AA,"[CID000004927, CID000003100, CID000002781]"

In [224]:
df_map_of_idx4ndc_rxcui_atc4_cids = pd.concat([
    df_drug_ndc_feat_ndc_real_rxcui_not_exist, 
    df_drug_ndc_feat_ndc_real,
    df_drug_ndc_feat_ndc_not_real
])
df_map_of_idx4ndc_rxcui_atc4_cids.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4294 entries, 416 to 4293
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NDC       4294 non-null   float64
 1   RXCUI     4101 non-null   float64
 2   idx       4294 non-null   int64
 3   ATC4      2885 non-null   object
 4   list_cid  2629 non-null   object
dtypes: float64(2), int64(1), object(2)
memory usage: 201.3+ KB

In [232]:
# df_map_of_idx4ndc_rxcui_atc4_cids.to_csv(os.path.join(path_ddi_dataset, "MAP_IDX4NDC_RXCUI_ATC4_CIDS.csv"))

## NDC index for whose CID exist

In [229]:
df_map_of_idx4ndc_rxcui_atc4_cids[df_map_of_idx4ndc_rxcui_atc4_cids.list_cid.notnull()]

,NDC,RXCUI,idx,ATC4,list_cid
1,2.140701e+06,853004.0,174,C01BA,"[CID000004914, CID000004913, CID000003114, CID..."
4,2.322930e+06,352320.0,177,N06BA,"[CID000054841, CID000003007, CID000004723, CID..."
5,2.323560e+06,596928.0,178,N06AX,"[CID000005533, CID000004449, CID000060835, CID..."
6,2.324001e+06,596932.0,179,N06AX,"[CID000005533, CID000004449, CID000060835, CID..."
7,2.324030e+06,596932.0,180,N06AX,"[CID000005533, CID000004449, CID000060835, CID..."
...,...,...,...,...,...
4082,6.854601e+10,637218.0,4272,N04BD,[CID000122316]
4086,6.877401e+10,197516.0,4276,J01FA,"[CID000054688, CID003002190, CID000002269, CID..."
4088,6.885000e+10,995605.0,4278,J04AK,"[CID000003279, CID000001046]"
4089,6.885000e+10,995609.0,4279,J04AK,"[CID000003279, CID000001046]"
4100,8.770108e+10,1049906.0,4292,D04AA,"[CID000004927, CID000003100, CID000002781]"

In [230]:
list_ndc_idx_can_calc_ddi = list(
    df_map_of_idx4ndc_rxcui_atc4_cids[df_map_of_idx4ndc_rxcui_atc4_cids.list_cid.notnull()]\
    .idx.unique()
)
list_ndc_idx_can_calc_ddi

# can be used for slide

[174,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 195,
 205,
 216,
 220,
 221,
 225,
 227,
 228,
 230,
 231,
 232,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 244,
 245,
 248,
 250,
 251,
 252,
 253,
 254,
 257,
 258,
 262,
 264,
 270,
 271,
 272,
 273,
 280,
 281,
 282,
 283,
 284,
 285,
 293,
 297,
 299,
 303,
 304,
 308,
 309,
 311,
 312,
 313,
 316,
 317,
 318,
 321,
 322,
 325,
 326,
 327,
 328,
 329,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 342,
 344,
 345,
 346,
 347,
 351,
 357,
 358,
 359,
 368,
 375,
 376,
 377,
 378,
 382,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 397,
 398,
 399,
 402,
 403,
 404,
 407,
 408,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 438,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 462,
 463,
 464,
 465,
 466,
 468,
 470,
 471,
 472,
 474,
 475,
 476,
 477,
 478,
 479,
 482,
 483,
 484,
 485,
 486,
 487,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 506,
 507,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 518,
 522,
 526,
 531,
 533,
 534,
 537,
 538,
 539,
 540,
 541,
 546,
 549,
 550,
 554,
 555,
 559,
 567,
 568,
 569,
 570,
 571,
 572,
 575,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 594,
 596,
 600,
 601,
 602,
 606,
 607,
 608,
 609,
 610,
 614,
 615,
 616,
 617,
 618,
 619,
 622,
 623,
 624,
 625,
 628,
 629,
 630,
 631,
 634,
 638,
 643,
 644,
 651,
 652,
 653,
 654,
 662,
 663,
 664,
 665,
 668,
 669,
 670,
 671,
 673,
 691,
 692,
 693,
 694,
 695,
 696,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 725,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 761,
 765,
 770,
 772,
 773,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 790,
 793,
 794,
 795,
 796,
 797,
 798,
 800,
 801,
 803,
 804,
 805,
 806,
 809,
 810,
 814,
 816,
 817,
 818,
 819,
 821,
 822,
 824,
 825,
 828,
 833,
 834,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 855,
 856,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 887,
 888,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 914,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 938,
 944,
 946,
 947,
 948,
 950,
 951,
 952,
 953,
 954,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1005,
 1006,
 1008,
 1011,
 1021,
 1024,
 1025,
 1026,
 1027,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1039,
 1040,
 1043,
 1045,
 1046,
 1047,
 1049,
 1053,
 1058,
 1060,
 1061,
 1062,
 1063,
 1065,
 1066,
 1070,
 1071,
 1076,
 1077,
 1079,
 1080,
 1081,
 1082,
 1085,
 1086,
 1087,
 1089,
 1091,
 1092,
 1093,
 1094,
 1095,
 1097,
 1098,
 1100,
 1102,
 1103,
 1105,
 1106,
 1109,
 1115,
 1119,
 1120,
 1121,
 1122,
 1124,
 1125,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1136,
 1137,
 1143,
 1144,
 1145,
 1148,
 1149,
 1150,
 1152,
 1153,
 1157,
 1159,
 1168,
 1169,
 1176,
 1177,
 1178,
 1181,
 1182,
 1183,
 1186,
 1188,
 1189,
 1190,
 1194,
 1195,
 1196,
 1197,
 1200,
 1201,
 1202,
 1209,
 1210,
 1211,
 1221,
 1222,
 1224,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1250,
 1252,
 1253,
 1255,
 1258,
 1259,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1275,
 1279,
 1280,
 1281,
 1282,
 1283,
 1285,
 1286,
 1287,
 1289,
 1290,
 1292,
 1293,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1325,
 1326,
 1328,
 1329,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 1343,
 1346,
 1348,
 1350,
 1352,
 1354,
 1355,
 1357,
 1358,
 1359,
 1362,
 1363,
 1364,
 1365,
 1366,
 1368,
 1370,
 1383,
 1385,
 1390,
 1391,
 1393,
 1394,
 1396,
 1398,
 1399,
 1403,
 1404,
 1405,
 1406,
 1407,
 1411,
 1412,
 1415,
 1416,
 1420,
 1424,
 1427,
 1429,
 1431,
 1433,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1449,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1492,
 1494,
 1496,
 1497,
 1499,
 1502,
 1504,
 1505,
 1506,
 1507,
 1509,
 1512,
 1515,
 1516,
 1517,
 1519,
 1520,
 1521,
 1523,
 1527,
 1528,
 1529,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1544,
 1547,
 1548,
 1549,
 1550,
 1551,
 1553,
 1554,
 1555,
 1556,
 1559,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1566,
 1567,
 1568,
 1569,
 1570,
 1571,
 1572,
 1573,
 1574,
 1575,
 1576,
 1579,
 1580,
 1581,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 1590,
 1591,
 1592,
 1593,
 1594,
 1595,
 1596,
 1597,
 1598,
 1599,
 1600,
 1601,
 1602,
 1603,
 1605,
 1606,
 1607,
 1608,
 1609,
 1610,
 1611,
 1612,
 1618,
 1620,
 1621,
 1622,
 1623,
 1624,
 1625,
 1626,
 1627,
 1628,
 1629,
 1630,
 1631,
 1632,
 1633,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1648,
 1649,
 1650,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1657,
 1658,
 1660,
 1662,
 1664,
 1665,
 1667,
 1669,
 1670,
 1674,
 1681,
 1682,
 1683,
 1684,
 1685,
 1686,
 1689,
 1690,
 1691,
 1693,
 1694,
 1696,
 1697,
 1698,
 1699,
 1700,
 1701,
 1702,
 1703,
 1705,
 1706,
 1707,
 1708,
 1711,
 1717,
 1718,
 1719,
 1720,
 1721,
 1722,
 1723,
 1725,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1732,
 1733,
 1735,
 1741,
 1743,
 1744,
 1745,
 1746,
 1747,
 1749,
 1751,
 1752,
 1754,
 1755,
 1758,
 1759,
 1760,
 1762,
 1763,
 1765,
 1767,
 1768,
 1769,
 1772,
 1773,
 ...]

In [231]:
len(list_ndc_idx_can_calc_ddi)

2629

# adjacency matrix of DDI

In [211]:
unique_exist_cid = []
for atc, list_cid in act2cid.items():
    unique_exist_cid.extend(list_cid)

unique_exist_cid = list(set(unique_exist_cid))  # make sure the uniqueness of cid
unique_exist_cid

['CID005311027',
 'CID000003954',
 'CID000060871',
 'CID000004914',
 'CID000005064',
 'CID000004724',
 'CID000003393',
 'CID000004594',
 'CID000004138',
 'CID000003961',
 'CID000005718',
 'CID000004062',
 'CID000005408',
 'CID000083786',
 'CID000004411',
 'CID000038904',
 'CID000125017',
 'CID000001206',
 'CID000005544',
 'CID000005403',
 'CID000005076',
 'CID000002130',
 'CID000002370',
 'CID000003964',
 'CID000051263',
 'CID000028112',
 'CID000156419',
 'CID000004536',
 'CID000004909',
 'CID000003417',
 'CID000002375',
 'CID000003648',
 'CID000006691',
 'CID000002905',
 'CID000006256',
 'CID001349907',
 'CID000034312',
 'CID000003114',
 'CID000004485',
 'CID000060835',
 'CID000003690',
 'CID000003366',
 'CID000003405',
 'CID000004915',
 'CID000005486',
 'CID000477468',
 'CID000005978',
 'CID000001978',
 'CID000005212',
 'CID000004197',
 'CID000060198',
 'CID000003040',
 'CID000213039',
 'CID000005040',
 'CID000005391',
 'CID000002727',
 'CID000004834',
 'CID000000951',
 'CID000005359',
 'CID000001065',
 'CID000005508',
 'CID000002435',
 'CID000003784',
 'CID000003310',
 'CID000003652',
 'CID000025419',
 'CID000002244',
 'CID000003350',
 'CID000003478',
 'CID000005878',
 'CID000002522',
 'CID000005732',
 'CID000002431',
 'CID000005775',
 'CID000002564',
 'CID000005572',
 'CID000005721',
 'CID000004891',
 'CID000003461',
 'CID004475485',
 'CID000005591',
 'CID003000502',
 'CID000005452',
 'CID000009034',
 'CID000003168',
 'CID000002550',
 'CID000004158',
 'CID000002083',
 'CID000003062',
 'CID000004170',
 'CID000005245',
 'CID000002512',
 'CID000003869',
 'CID000003157',
 'CID000023897',
 'CID000004054',
 'CID000002955',
 'CID000002267',
 'CID000040159',
 'CID000004934',
 'CID000002021',
 'CID000003372',
 'CID000004078',
 'CID000004436',
 'CID000003016',
 'CID005282226',
 'CID000004195',
 'CID000056339',
 'CID000005155',
 'CID000054374',
 'CID000004189',
 'CID003085017',
 'CID000005593',
 'CID000004609',
 'CID000000681',
 'CID000041781',
 'CID000005203',
 'CID000004727',
 'CID000004140',
 'CID000048041',
 'CID000004212',
 'CID000003950',
 'CID000002315',
 'CID000003324',
 'CID005281104',
 'CID000002474',
 'CID000004428',
 'CID000005496',
 'CID000123631',
 'CID000003325',
 'CID000002519',
 'CID000003749',
 'CID000000853',
 'CID000002022',
 'CID000060865',
 'CID000005665',
 'CID000004160',
 'CID000002678',
 'CID000005546',
 'CID000002162',
 'CID000005719',
 'CID000002656',
 'CID000002676',
 'CID004183806',
 'CID000003007',
 'CID000003032',
 'CID000160051',
 'CID000104741',
 'CID000005412',
 'CID000003780',
 'CID000030623',
 'CID000003559',
 'CID000003381',
 'CID000002133',
 'CID000002462',
 'CID000002708',
 'CID000060184',
 'CID000004030',
 'CID000004513',
 'CID000004052',
 'CID000004547',
 'CID000151165',
 'CID000001546',
 'CID000047725',
 'CID000002266',
 'CID000016362',
 'CID000003419',
 'CID000077993',
 'CID000082146',
 'CID000150610',
 'CID000004107',
 'CID000004539',
 'CID000003685',
 'CID000004171',
 'CID000000450',
 'CID000060753',
 'CID000064147',
 'CID000004666',
 'CID000057469',
 'CID000002123',
 'CID000005454',
 'CID000001935',
 'CID000031477',
 'CID000002283',
 'CID000005039',
 'CID005362070',
 'CID000002265',
 'CID000006476',
 'CID000002559',
 'CID000004509',
 'CID000004173',
 'CID000005650',
 'CID005329102',
 'CID000003475',
 'CID005311039',
 'CID000003825',
 'CID000002585',
 'CID000004635',
 'CID000005152',
 'CID000013342',
 'CID000060879',
 'CID000004908',
 'CID000122316',
 'CID000005379',
 'CID000005503',
 'CID000003340',
 'CID000002631',
 'CID000003657',
 'CID000002675',
 'CID000002629',
 'CID000004058',
 'CID000041693',
 'CID000004927',
 'CID000072938',
 'CID000005625',
 'CID000157922',
 'CID000000861',
 'CID000003406',
 'CID000003937',
 'CID000002578',
 'CID006398970',
 'CID000123620',
 'CID000072467',
 'CID000016231',
 'CID000002369',
 'CID000004993',
 'CID000003355',
 'CID000002215',
 'CID000003449',
 'CID000176870',
 'CID000002749',
 'CID000002907',
 'CID000001775',
 'CID000040976',
 'CID000163742',
 'CID000059768',
 'CID000002891',
 'CID000003821',
 'CID000062867',
 'CID000004976',
 'CID000005193',
 'CID000039765',
 'CID000002913',
 'CID000002751',
 'CID000002476',
 'CID000003902',
 'CID000003382',
 'CID004659569',
 'CID005493444',
 'CID000004168',
 'CID000039860',
 'CID000000581',
 'CID000004689',
 'CID000005472',
 'CID004659568',
 'CID006323497',
 'CID000008953',
 'CID000003463',
 'CID000003914',
 'CID000004211',
 'CID000002725',
 'CID000003158',
 'CID000002160',
 'CID000002973',
 'CID000071329',
 'CID000032797',
 'CID000005267',
 'CID000004046',
 'CID000002610',
 'CID000004449',
 'CID005281007',
 'CID000004057',
 'CID000003878',
 'CID005487301',
 'CID000002405',
 'CID000003117',
 'CID000004112',
 'CID000048175',
 'CID005381226',
 'CID000018140',
 'CID000010548',
 'CID000003675',
 'CID000003019',
 'CID000000143',
 'CID000002153',
 'CID000091270',
 'CID000003639',
 'CID006436173',
 'CID000004829',
 'CID000124087',
 'CID000003759',
 'CID000005035',
 'CID000005300',
 'CID000003161',
 'CID000003394',
 'CID000004935',
 'CID000002443',
 'CID000003339',
 'CID000060164',
 'CID000001986',
 'CID000004893',
 'CID000003883',
 'CID000004543',
 'CID000004497',
 'CID000110635',
 'CID000004205',
 'CID000002344',
 'CID006398525',
 'CID000005396',
 'CID000002311',
 'CID000002666',
 'CID000123606',
 'CID000003750',
 'CID000003385',
 'CID000002658',
 'CID000005516',
 'CID000002732',
 'CID000003365',
 'CID000004200',
 'CID000002646',
 'CID000060147',
 'CID000005401',
 'CID000004409',
 'CID000004425',
 'CID000004506',
 'CID000004856',
 'CID000002978',
 'CID000005358',
 'CID000006058',
 'CID003062316',
 'CID000000596',
 'CID000004913',
 'CID000004946',
 'CID000002554',
 'CID005481350',
 'CID000003823',
 'CID000438204',
 'CID000005038',
 'CID000060787',
 'CID000003241',
 'CID000036811',
 'CID000003384',
 'CID000002477',
 'CID000004616',
 'CID000060843',
 'CID000004595',
 'CID000003962',
 'CID000004920',
 'CID000005731',
 'CID000002308',
 'CID000000298',
 'CID000054454',
 'CID000056959',
 'CID000047320',
 'CID000004845',
 'CID000074989',
 'CID000004075',
 'CID000003414',
 'CID000004095',
 'CID000004900',
 'CID000002487',
 'CID000002249',
 'CID000003291',
 'CID000004737',
 'CID000004873',
 'CID000002995',
 'CID000005672',
 'CID005282044',
 'CID000065999',
 'CID000068740',
 'CID000003105',
 'CID000002179',
 'CID000005466',
 'CID000050614',
 'CID000077992',
 'CID000130881',
 'CID000072054',
 'CID000000453',
 'CID000005566',
 'CID000068844',
 'CID000003440',
 'CID000004723',
 'CID000003877',
 'CID000657298',
 'CID000005352',
 'CID000002471',
 'CID000009433',
 'CID000002712',
 'CID009571074',
 'CID000005538',
 'CID000000942',
 'CID000060854',
 'CID005311181',
 'CID000002802',
 'CID000002284',
 'CID000002617',
 'CID000054841',
 'CID000004730',
 'CID000110634',
 'CID005353980',
 'CID000003397',
 'CID000052421',
 'CID000002895',
 'CID000004259',
 'CID000005291',
 'CID000003354',
 'CID000002806',
 'CID000002082',
 'CID000004674',
 'CID000004768',
 'CID000002756',
 'CID000003476',
 'CID000004739',
 'CID005311297',
 'CID000003698',
 'CID000005645',
 'CID000005735',
 'CID000002726',
 'CID000060696',
 'CID000002713',
 'CID000002583',
 'CID000054786',
 'CID000004121',
 'CID000005078',
 'CID000005504',
 'CID000005526',
 'CID000041774',
 'CID000077999',
 'CID000005596',
 'CID000005512',
 'CID000002520',
 'CID000059708',
 'CID000002673',
 'CID000004634',
 'CID000004911',
 'CID000003100',
 'CID000005525',
 'CID000005430',
 'CID000004623',
 'CID000170361',
 'CID000005005',
 'CID000003373',
 'CID000003510',
 'CID000005651',
 'CID000003305',
 'CID000002662',
 'CID000003342',
 'CID000004440',
 'CID000060707',
 'CID000004053',
 'CID000002637',
 'CID000003488',
 'CID000000727',
 'CID000003387',
 'CID006447131',
 'CID000005746',
 'CID005361912',
 'CID000002650',
 'CID000003292',
 'CID000131536',
 'CID000002655',
 'CID000060852',
 'CID000005505',
 'CID000002145',
 'CID000002182',
 'CID000003890',
 'CID000005582',
 'CID000002170',
 'CID000002786',
 'CID000002232',
 'CID000667490',
 'CID000004614',
 'CID000060169',
 'CID000027991',
 'CID000003392',
 'CID000002088',
 'CID000027661',
 'CID000003279',
 'CID005311048',
 'CID000001971',
 'CID000005578',
 'CID000003042',
 'CID000003826',
 'CID000004201',
 'CID000001046',
 'CID000003308',
 'CID000003203',
 'CID000005215',
 'CID000002187',
 'CID000002171',
 'CID000004419',
 'CID000041744',
 'CID000005556',
 'CID000003779',
 'CID000036339',
 'CID000002156',
 'CID000000159',
 'CID000004192',
 'CID000150311',
 'CID000004828',
 'CID000005726',
 'CID000004607',
 'CID000004542',
 'CID000047319',
 'CID000000838',
 'CID000004463',
 'CID000003333',
 'CID000071273',
 'CID000005253',
 'CID000004943',
 'CID000003915',
 'CID000000187',
 'CID000071158',
 'CID000002609',
 'CID000443871',
 'CID000004819',
 'CID000003658',
 'CID000060815',
 'CID000003278',
 'CID000002478',
 'CID000000158',
 'CID000002781',
 'CID000002524',
 'CID000062816',
 'CID000005717',
 'CID000004159',
 'CID005353894',
 'CID000003672',
 'CID000004451',
 'CID000003706',
 'CID000002173',
 'CID000001972',
 'CID000154059',
 'CID000005453',
 'CID000002381',
 'CID000003958',
 'CID004479097',
 'CID000002250',
 'CID000003121',
 'CID000002812',
 'CID000002441',
 'CID000150310',
 'CID000004510',
 'CID000093860',
 'CID000002541',
 'CID000002803',
 'CID000003957',
 'CID000003375',
 'CID000004178',
 'CID000003647',
 'CID000004236',
 'CID000003003',
 'CID000005647',
 'CID000003899',
 'CID000504578',
 'CID000002216',
 'CID000041317',
 'CID000002818',
 'CID000003454',
 'CID000005478',
 'CID000005376',
 'CID000004603',
 'CID000004100',
 'CID000004011',
 'CID000003151',
 'CID000004253',
 'CID000005533',
 'CID000003148',
 'CID000002141',
 'CID000003467',
 'CID000003403',
 'CID000004748',
 'CID000005297',
 'CID000005584',
 'CID000005487',
 'CID000060937',
 'CID000062959',
 'CID000004889',
 'CID000054688',
 'CID000005515',
 'CID000003000',
 'CID000002131',
 'CID000003059',
 'CID000148211',
 'CID000004264',
 'CID011947681',
 'CID000002269',
 'CID000003222',
 'CID000005071',
 'CID000003702',
 'CID000002551',
 'CID000115237',
 'CID000004675',
 'CID000000772',
 'CID000003348',
 'CID000002951',
 'CID000004645',
 'CID000004894',
 'CID000000137',
 'CID000002177',
 'CID000003637',
 'CID000004919',
 'CID000005381',
 'CID000003261',
 'CID000003410',
 'CID003002190',
 'CID000096312',
 'CID000019090',
 'CID000071301',
 'CID000003929',
 'CID005473385',
 'CID000004991',
 'CID000050294',
 'CID000039042',
 'CID000060613',
 'CID000014888',
 'CID000051577',
 'CID000031378',
 'CID000003793',
 'CID000003519',
 'CID000002274',
 'CID000004060',
 'CID000003746',
 'CID000004493',
 'CID000027686',
 'CID000002958',
 'CID000000888',
 'CID000005342',
 'CID000002719',
 'CID000005404',
 'CID000000401',
 'CID000004870',
 'CID000000085',
 'CID000005314',
 'CID000005002',
 'CID000000750',
 'CID000004091',
 'CID000000191',
 'CID000060612',
 'CID000002142',
 'CID000104758',
 'CID000001148',
 'CID000003948',
 'CID000002622',
 'CID004630253',
 'CID000003143',
 'CID000003367',
 'CID003468412',
 'CID000003494',
 'CID000003661',
 'CID000004917',
 'CID000065027',
 'CID000087177',
 'CID000003715',
 'CID000003827',
 'CID000003676',
 'CID000002092',
 'CID000002349',
 'CID000003043',
 'CID000000815',
 'CID000002769',
 'CID000004932',
 'CID000003767',
 'CID000002983',
 'CID000005734',
 'CID000002118',
 'CID000005394',
 'CID000002720',
 'CID000004473',
 'CID000104803',
 'CID000003696',
 'CID000054547',
 'CID000005402',
 'CID000003255',
 'CID000003108']

In [212]:
len(unique_exist_cid)

675

In [213]:
def cmp_cid(cid: str):
    return int(cid[3:])
    
unique_exist_cid.sort(key=cmp_cid)
unique_exist_cid

['CID000000085',
 'CID000000137',
 'CID000000143',
 'CID000000158',
 'CID000000159',
 'CID000000187',
 'CID000000191',
 'CID000000298',
 'CID000000401',
 'CID000000450',
 'CID000000453',
 'CID000000581',
 'CID000000596',
 'CID000000681',
 'CID000000727',
 'CID000000750',
 'CID000000772',
 'CID000000815',
 'CID000000838',
 'CID000000853',
 'CID000000861',
 'CID000000888',
 'CID000000942',
 'CID000000951',
 'CID000001046',
 'CID000001065',
 'CID000001148',
 'CID000001206',
 'CID000001546',
 'CID000001775',
 'CID000001935',
 'CID000001971',
 'CID000001972',
 'CID000001978',
 'CID000001986',
 'CID000002021',
 'CID000002022',
 'CID000002082',
 'CID000002083',
 'CID000002088',
 'CID000002092',
 'CID000002118',
 'CID000002123',
 'CID000002130',
 'CID000002131',
 'CID000002133',
 'CID000002141',
 'CID000002142',
 'CID000002145',
 'CID000002153',
 'CID000002156',
 'CID000002160',
 'CID000002162',
 'CID000002170',
 'CID000002171',
 'CID000002173',
 'CID000002177',
 'CID000002179',
 'CID000002182',
 'CID000002187',
 'CID000002215',
 'CID000002216',
 'CID000002232',
 'CID000002244',
 'CID000002249',
 'CID000002250',
 'CID000002265',
 'CID000002266',
 'CID000002267',
 'CID000002269',
 'CID000002274',
 'CID000002283',
 'CID000002284',
 'CID000002308',
 'CID000002311',
 'CID000002315',
 'CID000002344',
 'CID000002349',
 'CID000002369',
 'CID000002370',
 'CID000002375',
 'CID000002381',
 'CID000002405',
 'CID000002431',
 'CID000002435',
 'CID000002441',
 'CID000002443',
 'CID000002462',
 'CID000002471',
 'CID000002474',
 'CID000002476',
 'CID000002477',
 'CID000002478',
 'CID000002487',
 'CID000002512',
 'CID000002519',
 'CID000002520',
 'CID000002522',
 'CID000002524',
 'CID000002541',
 'CID000002550',
 'CID000002551',
 'CID000002554',
 'CID000002559',
 'CID000002564',
 'CID000002578',
 'CID000002583',
 'CID000002585',
 'CID000002609',
 'CID000002610',
 'CID000002617',
 'CID000002622',
 'CID000002629',
 'CID000002631',
 'CID000002637',
 'CID000002646',
 'CID000002650',
 'CID000002655',
 'CID000002656',
 'CID000002658',
 'CID000002662',
 'CID000002666',
 'CID000002673',
 'CID000002675',
 'CID000002676',
 'CID000002678',
 'CID000002708',
 'CID000002712',
 'CID000002713',
 'CID000002719',
 'CID000002720',
 'CID000002725',
 'CID000002726',
 'CID000002727',
 'CID000002732',
 'CID000002749',
 'CID000002751',
 'CID000002756',
 'CID000002769',
 'CID000002781',
 'CID000002786',
 'CID000002802',
 'CID000002803',
 'CID000002806',
 'CID000002812',
 'CID000002818',
 'CID000002891',
 'CID000002895',
 'CID000002905',
 'CID000002907',
 'CID000002913',
 'CID000002951',
 'CID000002955',
 'CID000002958',
 'CID000002973',
 'CID000002978',
 'CID000002983',
 'CID000002995',
 'CID000003000',
 'CID000003003',
 'CID000003007',
 'CID000003016',
 'CID000003019',
 'CID000003032',
 'CID000003040',
 'CID000003042',
 'CID000003043',
 'CID000003059',
 'CID000003062',
 'CID000003100',
 'CID000003105',
 'CID000003108',
 'CID000003114',
 'CID000003117',
 'CID000003121',
 'CID000003143',
 'CID000003148',
 'CID000003151',
 'CID000003157',
 'CID000003158',
 'CID000003161',
 'CID000003168',
 'CID000003203',
 'CID000003222',
 'CID000003241',
 'CID000003255',
 'CID000003261',
 'CID000003278',
 'CID000003279',
 'CID000003291',
 'CID000003292',
 'CID000003305',
 'CID000003308',
 'CID000003310',
 'CID000003324',
 'CID000003325',
 'CID000003333',
 'CID000003339',
 'CID000003340',
 'CID000003342',
 'CID000003348',
 'CID000003350',
 'CID000003354',
 'CID000003355',
 'CID000003365',
 'CID000003366',
 'CID000003367',
 'CID000003372',
 'CID000003373',
 'CID000003375',
 'CID000003381',
 'CID000003382',
 'CID000003384',
 'CID000003385',
 'CID000003387',
 'CID000003392',
 'CID000003393',
 'CID000003394',
 'CID000003397',
 'CID000003403',
 'CID000003405',
 'CID000003406',
 'CID000003410',
 'CID000003414',
 'CID000003417',
 'CID000003419',
 'CID000003440',
 'CID000003449',
 'CID000003454',
 'CID000003461',
 'CID000003463',
 'CID000003467',
 'CID000003475',
 'CID000003476',
 'CID000003478',
 'CID000003488',
 'CID000003494',
 'CID000003510',
 'CID000003519',
 'CID000003559',
 'CID000003637',
 'CID000003639',
 'CID000003647',
 'CID000003648',
 'CID000003652',
 'CID000003657',
 'CID000003658',
 'CID000003661',
 'CID000003672',
 'CID000003675',
 'CID000003676',
 'CID000003685',
 'CID000003690',
 'CID000003696',
 'CID000003698',
 'CID000003702',
 'CID000003706',
 'CID000003715',
 'CID000003746',
 'CID000003749',
 'CID000003750',
 'CID000003759',
 'CID000003767',
 'CID000003779',
 'CID000003780',
 'CID000003784',
 'CID000003793',
 'CID000003821',
 'CID000003823',
 'CID000003825',
 'CID000003826',
 'CID000003827',
 'CID000003869',
 'CID000003877',
 'CID000003878',
 'CID000003883',
 'CID000003890',
 'CID000003899',
 'CID000003902',
 'CID000003914',
 'CID000003915',
 'CID000003929',
 'CID000003937',
 'CID000003948',
 'CID000003950',
 'CID000003954',
 'CID000003957',
 'CID000003958',
 'CID000003961',
 'CID000003962',
 'CID000003964',
 'CID000004011',
 'CID000004030',
 'CID000004046',
 'CID000004052',
 'CID000004053',
 'CID000004054',
 'CID000004057',
 'CID000004058',
 'CID000004060',
 'CID000004062',
 'CID000004075',
 'CID000004078',
 'CID000004091',
 'CID000004095',
 'CID000004100',
 'CID000004107',
 'CID000004112',
 'CID000004121',
 'CID000004138',
 'CID000004140',
 'CID000004158',
 'CID000004159',
 'CID000004160',
 'CID000004168',
 'CID000004170',
 'CID000004171',
 'CID000004173',
 'CID000004178',
 'CID000004189',
 'CID000004192',
 'CID000004195',
 'CID000004197',
 'CID000004200',
 'CID000004201',
 'CID000004205',
 'CID000004211',
 'CID000004212',
 'CID000004236',
 'CID000004253',
 'CID000004259',
 'CID000004264',
 'CID000004409',
 'CID000004411',
 'CID000004419',
 'CID000004425',
 'CID000004428',
 'CID000004436',
 'CID000004440',
 'CID000004449',
 'CID000004451',
 'CID000004463',
 'CID000004473',
 'CID000004485',
 'CID000004493',
 'CID000004497',
 'CID000004506',
 'CID000004509',
 'CID000004510',
 'CID000004513',
 'CID000004536',
 'CID000004539',
 'CID000004542',
 'CID000004543',
 'CID000004547',
 'CID000004594',
 'CID000004595',
 'CID000004603',
 'CID000004607',
 'CID000004609',
 'CID000004614',
 'CID000004616',
 'CID000004623',
 'CID000004634',
 'CID000004635',
 'CID000004645',
 'CID000004666',
 'CID000004674',
 'CID000004675',
 'CID000004689',
 'CID000004723',
 'CID000004724',
 'CID000004727',
 'CID000004730',
 'CID000004737',
 'CID000004739',
 'CID000004748',
 'CID000004768',
 'CID000004819',
 'CID000004828',
 'CID000004829',
 'CID000004834',
 'CID000004845',
 'CID000004856',
 'CID000004870',
 'CID000004873',
 'CID000004889',
 'CID000004891',
 'CID000004893',
 'CID000004894',
 'CID000004900',
 'CID000004908',
 'CID000004909',
 'CID000004911',
 'CID000004913',
 'CID000004914',
 'CID000004915',
 'CID000004917',
 'CID000004919',
 'CID000004920',
 'CID000004927',
 'CID000004932',
 'CID000004934',
 'CID000004935',
 'CID000004943',
 'CID000004946',
 'CID000004976',
 'CID000004991',
 'CID000004993',
 'CID000005002',
 'CID000005005',
 'CID000005035',
 'CID000005038',
 'CID000005039',
 'CID000005040',
 'CID000005064',
 'CID000005071',
 'CID000005076',
 'CID000005078',
 'CID000005152',
 'CID000005155',
 'CID000005193',
 'CID000005203',
 'CID000005212',
 'CID000005215',
 'CID000005245',
 'CID000005253',
 'CID000005267',
 'CID000005291',
 'CID000005297',
 'CID000005300',
 'CID000005314',
 'CID000005342',
 'CID000005352',
 'CID000005358',
 'CID000005359',
 'CID000005376',
 'CID000005379',
 'CID000005381',
 'CID000005391',
 'CID000005394',
 'CID000005396',
 'CID000005401',
 'CID000005402',
 'CID000005403',
 'CID000005404',
 'CID000005408',
 'CID000005412',
 'CID000005430',
 'CID000005452',
 'CID000005453',
 'CID000005454',
 'CID000005466',
 'CID000005472',
 'CID000005478',
 'CID000005486',
 'CID000005487',
 'CID000005496',
 'CID000005503',
 'CID000005504',
 'CID000005505',
 'CID000005508',
 'CID000005512',
 'CID000005515',
 'CID000005516',
 'CID000005525',
 'CID000005526',
 'CID000005533',
 'CID000005538',
 'CID000005544',
 'CID000005546',
 'CID000005556',
 'CID000005566',
 'CID000005572',
 'CID000005578',
 'CID000005582',
 'CID000005584',
 'CID000005591',
 'CID000005593',
 'CID000005596',
 'CID000005625',
 'CID000005645',
 'CID000005647',
 'CID000005650',
 'CID000005651',
 'CID000005665',
 'CID000005672',
 'CID000005717',
 'CID000005718',
 'CID000005719',
 'CID000005721',
 'CID000005726',
 'CID000005731',
 'CID000005732',
 'CID000005734',
 'CID000005735',
 'CID000005746',
 'CID000005775',
 'CID000005878',
 'CID000005978',
 'CID000006058',
 'CID000006256',
 'CID000006476',
 'CID000006691',
 'CID000008953',
 'CID000009034',
 'CID000009433',
 'CID000010548',
 'CID000013342',
 'CID000014888',
 'CID000016231',
 'CID000016362',
 'CID000018140',
 'CID000019090',
 'CID000023897',
 'CID000025419',
 'CID000027661',
 'CID000027686',
 'CID000027991',
 'CID000028112',
 'CID000030623',
 'CID000031378',
 'CID000031477',
 'CID000032797',
 'CID000034312',
 'CID000036339',
 'CID000036811',
 'CID000038904',
 'CID000039042',
 'CID000039765',
 'CID000039860',
 'CID000040159',
 'CID000040976',
 'CID000041317',
 'CID000041693',
 'CID000041744',
 'CID000041774',
 'CID000041781',
 'CID000047319',
 'CID000047320',
 'CID000047725',
 'CID000048041',
 'CID000048175',
 'CID000050294',
 'CID000050614',
 'CID000051263',
 'CID000051577',
 'CID000052421',
 'CID000054374',
 'CID000054454',
 'CID000054547',
 'CID000054688',
 'CID000054786',
 'CID000054841',
 'CID000056339',
 'CID000056959',
 'CID000057469',
 'CID000059708',
 'CID000059768',
 'CID000060147',
 'CID000060164',
 'CID000060169',
 'CID000060184',
 'CID000060198',
 'CID000060612',
 'CID000060613',
 'CID000060696',
 'CID000060707',
 'CID000060753',
 'CID000060787',
 'CID000060815',
 'CID000060835',
 'CID000060843',
 'CID000060852',
 'CID000060854',
 'CID000060865',
 'CID000060871',
 'CID000060879',
 'CID000060937',
 'CID000062816',
 'CID000062867',
 'CID000062959',
 'CID000064147',
 'CID000065027',
 'CID000065999',
 'CID000068740',
 'CID000068844',
 'CID000071158',
 'CID000071273',
 'CID000071301',
 'CID000071329',
 'CID000072054',
 'CID000072467',
 'CID000072938',
 'CID000074989',
 'CID000077992',
 'CID000077993',
 'CID000077999',
 'CID000082146',
 'CID000083786',
 'CID000087177',
 'CID000091270',
 'CID000093860',
 'CID000096312',
 'CID000104741',
 'CID000104758',
 'CID000104803',
 'CID000110634',
 'CID000110635',
 'CID000115237',
 'CID000122316',
 'CID000123606',
 'CID000123620',
 'CID000123631',
 'CID000124087',
 'CID000125017',
 'CID000130881',
 'CID000131536',
 'CID000148211',
 'CID000150310',
 'CID000150311',
 'CID000150610',
 'CID000151165',
 'CID000154059',
 'CID000156419',
 'CID000157922',
 'CID000160051',
 'CID000163742',
 'CID000170361',
 'CID000176870',
 'CID000213039',
 'CID000438204',
 'CID000443871',
 'CID000477468',
 'CID000504578',
 'CID000657298',
 'CID000667490',
 'CID001349907',
 'CID003000502',
 'CID003002190',
 'CID003062316',
 'CID003085017',
 'CID003468412',
 'CID004183806',
 'CID004475485',
 'CID004479097',
 'CID004630253',
 'CID004659568',
 'CID004659569',
 'CID005281007',
 'CID005281104',
 'CID005282044',
 'CID005282226',
 'CID005311027',
 'CID005311039',
 'CID005311048',
 'CID005311181',
 'CID005311297',
 'CID005329102',
 'CID005353894',
 'CID005353980',
 'CID005361912',
 'CID005362070',
 'CID005381226',
 'CID005473385',
 'CID005481350',
 'CID005487301',
 'CID005493444',
 'CID006323497',
 'CID006398525',
 'CID006398970',
 'CID006436173',
 'CID006447131',
 'CID009571074',
 'CID011947681']

In [214]:
map_cid2idx = pd.Series(data=range(len(unique_exist_cid)), index=unique_exist_cid)
map_cid2idx

CID000000085      0
CID000000137      1
CID000000143      2
CID000000158      3
CID000000159      4
               ...
CID006398970    670
CID006436173    671
CID006447131    672
CID009571074    673
CID011947681    674
Length: 675, dtype: int64

In [235]:
df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist     = df_map_of_idx4ndc_rxcui_atc4_cids[df_map_of_idx4ndc_rxcui_atc4_cids.list_cid.notnull()].copy()
df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_not_exist = df_map_of_idx4ndc_rxcui_atc4_cids[df_map_of_idx4ndc_rxcui_atc4_cids.list_cid.isnull()].copy()

df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist

,NDC,RXCUI,idx,ATC4,list_cid
1,2.140701e+06,853004.0,174,C01BA,"[CID000004914, CID000004913, CID000003114, CID..."
4,2.322930e+06,352320.0,177,N06BA,"[CID000054841, CID000003007, CID000004723, CID..."
5,2.323560e+06,596928.0,178,N06AX,"[CID000005533, CID000004449, CID000060835, CID..."
6,2.324001e+06,596932.0,179,N06AX,"[CID000005533, CID000004449, CID000060835, CID..."
7,2.324030e+06,596932.0,180,N06AX,"[CID000005533, CID000004449, CID000060835, CID..."
...,...,...,...,...,...
4082,6.854601e+10,637218.0,4272,N04BD,[CID000122316]
4086,6.877401e+10,197516.0,4276,J01FA,"[CID000054688, CID003002190, CID000002269, CID..."
4088,6.885000e+10,995605.0,4278,J04AK,"[CID000003279, CID000001046]"
4089,6.885000e+10,995609.0,4279,J04AK,"[CID000003279, CID000001046]"
4100,8.770108e+10,1049906.0,4292,D04AA,"[CID000004927, CID000003100, CID000002781]"

In order to speed up the calculation of DDI, the CID list needs to be converted into a CID index list in advance.

In [237]:
def list_cid2list_cid_idx(list_cid):
    return [map_cid2idx[cid] for cid in list_cid]

df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist['list_cid_idx'] = \
df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist['list_cid'].apply(list_cid2list_cid_idx)

df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist

,NDC,RXCUI,idx,ATC4,list_cid,list_cid_idx
1,2.140701e+06,853004.0,174,C01BA,"[CID000004914, CID000004913, CID000003114, CID...","[395, 394, 172, 25]"
4,2.322930e+06,352320.0,177,N06BA,"[CID000054841, CID000003007, CID000004723, CID...","[553, 160, 370, 311, 328, 27]"
5,2.323560e+06,596928.0,178,N06AX,"[CID000005533, CID000004449, CID000060835, CID...","[467, 339, 571, 325, 615, 26]"
6,2.324001e+06,596932.0,179,N06AX,"[CID000005533, CID000004449, CID000060835, CID...","[467, 339, 571, 325, 615, 26]"
7,2.324030e+06,596932.0,180,N06AX,"[CID000005533, CID000004449, CID000060835, CID...","[467, 339, 571, 325, 615, 26]"
...,...,...,...,...,...,...
4082,6.854601e+10,637218.0,4272,N04BD,[CID000122316],[610]
4086,6.877401e+10,197516.0,4276,J01FA,"[CID000054688, CID003002190, CID000002269, CID...","[551, 639, 69, 185]"
4088,6.885000e+10,995605.0,4278,J04AK,"[CID000003279, CID000001046]","[188, 24]"
4089,6.885000e+10,995609.0,4279,J04AK,"[CID000003279, CID000001046]","[188, 24]"
4100,8.770108e+10,1049906.0,4292,D04AA,"[CID000004927, CID000003100, CID000002781]","[400, 169, 139]"

In [254]:
list(
    df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist.head().list_cid_idx.values
)

[[395, 394, 172, 25],
 [553, 160, 370, 311, 328, 27],
 [467, 339, 571, 325, 615, 26],
 [467, 339, 571, 325, 615, 26],
 [467, 339, 571, 325, 615, 26]]

In [239]:
df_map_of_idx4ndc_rxcui_atc4_cids = pd.concat([
    df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_not_exist,
    df_map_of_idx4ndc_rxcui_atc4_cids_list_cid_exist
])
df_map_of_idx4ndc_rxcui_atc4_cids

,NDC,RXCUI,idx,ATC4,list_cid,list_cid_idx
416,2.606320e+07,NaN,589,NaN,NaN,NaN
1351,1.320001e+08,NaN,1524,NaN,NaN,NaN
1798,3.380404e+08,NaN,1971,NaN,NaN,NaN
2569,8.290002e+09,NaN,2742,NaN,NaN,NaN
2576,8.881200e+09,NaN,2749,NaN,NaN,NaN
...,...,...,...,...,...,...
4082,6.854601e+10,637218.0,4272,N04BD,[CID000122316],[610]
4086,6.877401e+10,197516.0,4276,J01FA,"[CID000054688, CID003002190, CID000002269, CID...","[551, 639, 69, 185]"
4088,6.885000e+10,995605.0,4278,J04AK,"[CID000003279, CID000001046]","[188, 24]"
4089,6.885000e+10,995609.0,4279,J04AK,"[CID000003279, CID000001046]","[188, 24]"
4100,8.770108e+10,1049906.0,4292,D04AA,"[CID000004927, CID000003100, CID000002781]","[400, 169, 139]"

In [240]:
df_map_of_idx4ndc_rxcui_atc4_cids.to_csv(os.path.join(path_ddi_dataset, "MAP_IDX4NDC_RXCUI_ATC4_CIDS.csv"))

## durg-DDI

In [69]:
df_drug_ddi = pd.read_csv(os.path.join(path_ddi_dataset, "drug-DDI.csv"))
df_drug_ddi

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name
0,CID000002173,CID000003345,C0151714,hypermagnesemia
1,CID000002173,CID000003345,C0035344,retinopathy of prematurity
2,CID000002173,CID000003345,C0004144,atelectasis
3,CID000002173,CID000003345,C0002063,alkalosis
4,CID000002173,CID000003345,C0004604,Back Ache
...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis
4649438,CID000003461,CID000003954,C0043096,loss of weight
4649439,CID000003461,CID000003954,C0003962,ascites
4649440,CID000003461,CID000003954,C0038999,bulging

In [160]:
df_drug_ddi_exist_cid = df_drug_ddi[df_drug_ddi["STITCH 1"].isin(unique_exist_cid) &
                                    df_drug_ddi["STITCH 2"].isin(unique_exist_cid)]
df_drug_ddi_exist_cid

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name
68,CID000003929,CID000150610,C0015230,eruption
69,CID000003929,CID000150610,C0001339,acute pancreatitis
70,CID000003929,CID000150610,C0032285,neumonia
71,CID000003929,CID000150610,C0013384,abnormal movements
72,CID000003929,CID000150610,C1145670,respiratory failure
...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis
4649438,CID000003461,CID000003954,C0043096,loss of weight
4649439,CID000003461,CID000003954,C0003962,ascites
4649440,CID000003461,CID000003954,C0038999,bulging

In [169]:
df_drug_ddi_exist_cid['idx_1'] = df_drug_ddi_exist_cid["STITCH 1"].map(map_cid2idx)
df_drug_ddi_exist_cid['idx_2'] = df_drug_ddi_exist_cid["STITCH 2"].map(map_cid2idx)
df_drug_ddi_exist_cid

/tmp/ipykernel_14242/3097511955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_drug_ddi_exist_cid['idx_1'] = df_drug_ddi_exist_cid["STITCH 1"].map(map_cid2idx)
/tmp/ipykernel_14242/3097511955.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_drug_ddi_exist_cid['idx_2'] = df_drug_ddi_exist_cid["STITCH 2"].map(map_cid2idx)

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name,idx_1,idx_2
68,CID000003929,CID000150610,C0015230,eruption,281,621
69,CID000003929,CID000150610,C0001339,acute pancreatitis,281,621
70,CID000003929,CID000150610,C0032285,neumonia,281,621
71,CID000003929,CID000150610,C0013384,abnormal movements,281,621
72,CID000003929,CID000150610,C1145670,respiratory failure,281,621
...,...,...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses,229,285
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis,229,285
4649438,CID000003461,CID000003954,C0043096,loss of weight,229,285
4649439,CID000003461,CID000003954,C0003962,ascites,229,285
4649440,CID000003461,CID000003954,C0038999,bulging,229,285

👆👆👆

We can find that for the same drug pair, there may have multiple interactions!

In [177]:
df_drug_ddi_exist_cid.drop_duplicates(subset=["idx_1", "idx_2"])

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name,idx_1,idx_2
68,CID000003929,CID000150610,C0015230,eruption,281,621
469,CID000004946,CID000130881,C0038454,apoplexy,405,616
533,CID000005391,CID000005584,C0009806,constipated,439,476
569,CID000002802,CID005381226,C0008325,cholecystitis,141,663
684,CID000000596,CID000005726,C0013221,drug toxicity NOS,12,491
...,...,...,...,...,...,...
4648536,CID000002978,CID003468412,C0043096,loss of weight,155,642
4648780,CID000003961,CID000005212,C0017152,gastric inflammation,288,423
4649252,CID000002477,CID000002541,C0522055,abnormal ECG,91,99
4649335,CID000003750,CID000027661,C0017152,gastric inflammation,260,516
4649370,CID000003461,CID000003954,C0042384,angiitis,229,285

In [181]:
ddi_adj = np.zeros(
    (len(unique_exist_cid), len(unique_exist_cid))
)

for index, row in tqdm(df_drug_ddi_exist_cid.iterrows()):
    ddi_adj[row['idx_1']][row['idx_2']] += 1
    ddi_adj[row['idx_2']][row['idx_1']] += 1
    
ddi_adj

0it [00:00, ?it/s]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 8., 0., 0.],
       ...,
       [0., 0., 8., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [183]:
ddi_adj.max()

540.0

In [184]:
ddi_adj.mean()

13.395300960219478

In [185]:
ddi_adj.std()

38.724570061541826

In [186]:
ddi_adj.min()

0.0

In [249]:
with open(os.path.join(path_ddi_dataset, "ddi_adj_matrix.pickle"), 'wb') as f:
    pickle.dump(ddi_adj, f)

## DDI calculate

The interaction between the cid_idx(s) of same drug should be omitted!

In [4]:
df_map_of_idx4ndc_rxcui_atc4_cids = pd.read_csv(os.path.join(path_ddi_dataset, "MAP_IDX4NDC_RXCUI_ATC4_CIDS.csv"))
df_map_of_idx4ndc_rxcui_atc4_cids

,Unnamed: 0,NDC,RXCUI,idx,ATC4,list_cid,list_cid_idx
0,416,2.606320e+07,NaN,589,NaN,NaN,NaN
1,1351,1.320001e+08,NaN,1524,NaN,NaN,NaN
2,1798,3.380404e+08,NaN,1971,NaN,NaN,NaN
3,2569,8.290002e+09,NaN,2742,NaN,NaN,NaN
4,2576,8.881200e+09,NaN,2749,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4289,4082,6.854601e+10,637218.0,4272,N04BD,['CID000122316'],[610]
4290,4086,6.877401e+10,197516.0,4276,J01FA,"['CID000054688', 'CID003002190', 'CID000002269...","[551, 639, 69, 185]"
4291,4088,6.885000e+10,995605.0,4278,J04AK,"['CID000003279', 'CID000001046']","[188, 24]"
4292,4089,6.885000e+10,995609.0,4279,J04AK,"['CID000003279', 'CID000001046']","[188, 24]"
4293,4100,8.770108e+10,1049906.0,4292,D04AA,"['CID000004927', 'CID000003100', 'CID000002781']","[400, 169, 139]"

In [5]:
with open(os.path.join(path_ddi_dataset, "ddi_adj_matrix.pickle"), 'rb') as f:
    ddi_adj = pickle.load(f)
    
ddi_adj

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 8., 0., 0.],
       ...,
       [0., 0., 8., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
def calc_ddi_rate(pred_drug_ndc_scores_per_admi: torch.BoolTensor, 
                  df_map_of_idx4ndc_rxcui_atc4_cids, 
                  ddi_adj):
    df_map_of_idx4ndc_rxcui_atc4_cids.sort_values(by='idx', inplace=True)
    df_drugs_curr_admi = df_map_of_idx4ndc_rxcui_atc4_cids.loc[
        pred_drug_ndc_scores_per_admi.cpu().detach().numpy()
    ]
    df_drugs_can_calc_ddi = df_drugs_curr_admi[df_drugs_curr_admi.list_cid_idx.notnull()]
    
    q = Queue()
    for list_cid_idx in list(df_drugs_can_calc_ddi.list_cid_idx.values):
        q.put(list_cid_idx)
    
    cnt_all_pair = 0
    cnt_ddi_pair = 0
    while q.qsize() > 1:
        list_curr_cid_idx = q.get()
        for curr_cid_idx in eval(list_curr_cid_idx):
            for list_other_cid_idx in q.queue:
                for other_cid_idx in eval(list_other_cid_idx):
                    if (ddi_adj[curr_cid_idx][other_cid_idx] != 0):
                        cnt_ddi_pair += 1
                    cnt_all_pair += 1
                
    return 0 if cnt_all_pair == 0 else cnt_ddi_pair / cnt_all_pair

pred_drug_ndc_scores_per_admi = torch.BoolTensor([False] * 4294)
pred_drug_ndc_scores_per_admi[4279] = True
pred_drug_ndc_scores_per_admi[4292] = True

calc_ddi_rate(pred_drug_ndc_scores_per_admi, 
              df_map_of_idx4ndc_rxcui_atc4_cids, 
              ddi_adj)

0.16666666666666666

In [49]:
# [188, 24]
# [400, 169, 139]
ddi_adj[188][400], ddi_adj[188][169], ddi_adj[188][139]

(32.0, 0.0, 0.0)

In [50]:
ddi_adj[24][400], ddi_adj[24][169], ddi_adj[24][139]

(0.0, 0.0, 0.0)